// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: src/core/config.proto

package core

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type PoolsChainConfig struct {
	VaultSize          uint64 `protobuf:"varint,1,opt,name=VaultSize,proto3" json:"VaultSize,omitempty"`
	BaseEth2DutyReward uint64 `protobuf:"varint,2,opt,name=BaseEth2DutyReward,proto3" json:"BaseEth2DutyReward,omitempty"`
	DKGReward          uint64 `protobuf:"varint,3,opt,name=DKGReward,proto3" json:"DKGReward,omitempty"`
	// slots and epochs
	SlotsInEpoch                 uint64   `protobuf:"varint,4,opt,name=SlotsInEpoch,proto3" json:"SlotsInEpoch,omitempty"`
	MinAttestationCommitteeSize  uint64   `protobuf:"varint,5,opt,name=MinAttestationCommitteeSize,proto3" json:"MinAttestationCommitteeSize,omitempty"`
	MaxAttestationCommitteeSize  uint64   `protobuf:"varint,6,opt,name=MaxAttestationCommitteeSize,proto3" json:"MaxAttestationCommitteeSize,omitempty"`
	MinAttestationInclusionDelay uint64   `protobuf:"varint,7,opt,name=MinAttestationInclusionDelay,proto3" json:"MinAttestationInclusionDelay,omitempty"`
	XXX_NoUnkeyedLiteral         struct{} `json:"-"`
	XXX_unrecognized             []byte   `json:"-"`
	XXX_sizecache                int32    `json:"-"`
}

func (m *PoolsChainConfig) Reset()         { *m = PoolsChainConfig{} }
func (m *PoolsChainConfig) String() string { return proto.CompactTextString(m) }
func (*PoolsChainConfig) ProtoMessage()    {}
func (*PoolsChainConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor_d0189c35229c86e3, []int{0}
}
func (m *PoolsChainConfig) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *PoolsChainConfig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_PoolsChainConfig.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *PoolsChainConfig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PoolsChainConfig.Merge(m, src)
}
func (m *PoolsChainConfig) XXX_Size() int {
	return m.Size()
}
func (m *PoolsChainConfig) XXX_DiscardUnknown() {
	xxx_messageInfo_PoolsChainConfig.DiscardUnknown(m)
}

var xxx_messageInfo_PoolsChainConfig proto.InternalMessageInfo

func (m *PoolsChainConfig) GetVaultSize() uint64 {
	if m != nil {
		return m.VaultSize
	}
	return 0
}

func (m *PoolsChainConfig) GetBaseEth2DutyReward() uint64 {
	if m != nil {
		return m.BaseEth2DutyReward
	}
	return 0
}

func (m *PoolsChainConfig) GetDKGReward() uint64 {
	if m != nil {
		return m.DKGReward
	}
	return 0
}

func (m *PoolsChainConfig) GetSlotsInEpoch() uint64 {
	if m != nil {
		return m.SlotsInEpoch
	}
	return 0
}

func (m *PoolsChainConfig) GetMinAttestationCommitteeSize() uint64 {
	if m != nil {
		return m.MinAttestationCommitteeSize
	}
	return 0
}

func (m *PoolsChainConfig) GetMaxAttestationCommitteeSize() uint64 {
	if m != nil {
		return m.MaxAttestationCommitteeSize
	}
	return 0
}

func (m *PoolsChainConfig) GetMinAttestationInclusionDelay() uint64 {
	if m != nil {
		return m.MinAttestationInclusionDelay
	}
	return 0
}

func init() {
	proto.RegisterType((*PoolsChainConfig)(nil), "state.PoolsChainConfig")
}

func init() { proto.RegisterFile("src/core/config.proto", fileDescriptor_d0189c35229c86e3) }

var fileDescriptor_d0189c35229c86e3 = []byte{
	// 258 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x2d, 0x2e, 0x4a, 0xd6,
	0x4f, 0xce, 0x2f, 0x4a, 0xd5, 0x4f, 0xce, 0xcf, 0x4b, 0xcb, 0x4c, 0xd7, 0x2b, 0x28, 0xca, 0x2f,
	0xc9, 0x17, 0x62, 0x2d, 0x2e, 0x49, 0x2c, 0x49, 0x55, 0x7a, 0xc5, 0xc4, 0x25, 0x10, 0x90, 0x9f,
	0x9f, 0x53, 0xec, 0x9c, 0x91, 0x98, 0x99, 0xe7, 0x0c, 0x56, 0x21, 0x24, 0xc3, 0xc5, 0x19, 0x96,
	0x58, 0x9a, 0x53, 0x12, 0x9c, 0x59, 0x95, 0x2a, 0xc1, 0xa8, 0xc0, 0xa8, 0xc1, 0x12, 0x84, 0x10,
	0x10, 0xd2, 0xe3, 0x12, 0x72, 0x4a, 0x2c, 0x4e, 0x75, 0x2d, 0xc9, 0x30, 0x72, 0x29, 0x2d, 0xa9,
	0x0c, 0x4a, 0x2d, 0x4f, 0x2c, 0x4a, 0x91, 0x60, 0x02, 0x2b, 0xc3, 0x22, 0x03, 0x32, 0xcd, 0xc5,
	0xdb, 0x1d, 0xaa, 0x8c, 0x19, 0x62, 0x1a, 0x5c, 0x40, 0x48, 0x89, 0x8b, 0x27, 0x38, 0x27, 0xbf,
	0xa4, 0xd8, 0x33, 0xcf, 0xb5, 0x20, 0x3f, 0x39, 0x43, 0x82, 0x05, 0xac, 0x00, 0x45, 0x4c, 0xc8,
	0x81, 0x4b, 0xda, 0x37, 0x33, 0xcf, 0xb1, 0xa4, 0x24, 0x15, 0xe4, 0xe8, 0xcc, 0xfc, 0x3c, 0xe7,
	0xfc, 0xdc, 0xdc, 0xcc, 0x92, 0x92, 0xd4, 0x54, 0xb0, 0x0b, 0x59, 0xc1, 0x5a, 0xf0, 0x29, 0x01,
	0x9b, 0x90, 0x58, 0x81, 0xd3, 0x04, 0x36, 0xa8, 0x09, 0xb8, 0x95, 0x08, 0x39, 0x71, 0xc9, 0xa0,
	0x5a, 0xe0, 0x99, 0x97, 0x9c, 0x53, 0x5a, 0x9c, 0x99, 0x9f, 0xe7, 0x92, 0x9a, 0x93, 0x58, 0x29,
	0xc1, 0x0e, 0x36, 0x02, 0xaf, 0x1a, 0x27, 0x89, 0x13, 0x8f, 0xe4, 0x18, 0x2f, 0x3c, 0x92, 0x63,
	0x7c, 0xf0, 0x48, 0x8e, 0x71, 0xc6, 0x63, 0x39, 0x86, 0x28, 0x36, 0x3d, 0x6b, 0x50, 0xd4, 0x24,
	0xb1, 0x81, 0x23, 0xc5, 0x18, 0x10, 0x00, 0x00, 0xff, 0xff, 0xa9, 0x28, 0x5c, 0xf7, 0xad, 0x01,
	0x00, 0x00,
}

func (m *PoolsChainConfig) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *PoolsChainConfig) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *PoolsChainConfig) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.XXX_unrecognized != nil {
		i -= len(m.XXX_unrecognized)
		copy(dAtA[i:], m.XXX_unrecognized)
	}
	if m.MinAttestationInclusionDelay != 0 {
		i = encodeVarintConfig(dAtA, i, uint64(m.MinAttestationInclusionDelay))
		i--
		dAtA[i] = 0x38
	}
	if m.MaxAttestationCommitteeSize != 0 {
		i = encodeVarintConfig(dAtA, i, uint64(m.MaxAttestationCommitteeSize))
		i--
		dAtA[i] = 0x30
	}
	if m.MinAttestationCommitteeSize != 0 {
		i = encodeVarintConfig(dAtA, i, uint64(m.MinAttestationCommitteeSize))
		i--
		dAtA[i] = 0x28
	}
	if m.SlotsInEpoch != 0 {
		i = encodeVarintConfig(dAtA, i, uint64(m.SlotsInEpoch))
		i--
		dAtA[i] = 0x20
	}
	if m.DKGReward != 0 {
		i = encodeVarintConfig(dAtA, i, uint64(m.DKGReward))
		i--
		dAtA[i] = 0x18
	}
	if m.BaseEth2DutyReward != 0 {
		i = encodeVarintConfig(dAtA, i, uint64(m.BaseEth2DutyReward))
		i--
		dAtA[i] = 0x10
	}
	if m.VaultSize != 0 {
		i = encodeVarintConfig(dAtA, i, uint64(m.VaultSize))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintConfig(dAtA []byte, offset int, v uint64) int {
	offset -= sovConfig(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *PoolsChainConfig) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.VaultSize != 0 {
		n += 1 + sovConfig(uint64(m.VaultSize))
	}
	if m.BaseEth2DutyReward != 0 {
		n += 1 + sovConfig(uint64(m.BaseEth2DutyReward))
	}
	if m.DKGReward != 0 {
		n += 1 + sovConfig(uint64(m.DKGReward))
	}
	if m.SlotsInEpoch != 0 {
		n += 1 + sovConfig(uint64(m.SlotsInEpoch))
	}
	if m.MinAttestationCommitteeSize != 0 {
		n += 1 + sovConfig(uint64(m.MinAttestationCommitteeSize))
	}
	if m.MaxAttestationCommitteeSize != 0 {
		n += 1 + sovConfig(uint64(m.MaxAttestationCommitteeSize))
	}
	if m.MinAttestationInclusionDelay != 0 {
		n += 1 + sovConfig(uint64(m.MinAttestationInclusionDelay))
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func sovConfig(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozConfig(x uint64) (n int) {
	return sovConfig(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *PoolsChainConfig) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowConfig
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: PoolsChainConfig: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: PoolsChainConfig: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field VaultSize", wireType)
			}
			m.VaultSize = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowConfig
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.VaultSize |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field BaseEth2DutyReward", wireType)
			}
			m.BaseEth2DutyReward = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowConfig
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.BaseEth2DutyReward |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field DKGReward", wireType)
			}
			m.DKGReward = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowConfig
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.DKGReward |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field SlotsInEpoch", wireType)
			}
			m.SlotsInEpoch = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowConfig
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.SlotsInEpoch |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MinAttestationCommitteeSize", wireType)
			}
			m.MinAttestationCommitteeSize = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowConfig
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MinAttestationCommitteeSize |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MaxAttestationCommitteeSize", wireType)
			}
			m.MaxAttestationCommitteeSize = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowConfig
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MaxAttestationCommitteeSize |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 7:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MinAttestationInclusionDelay", wireType)
			}
			m.MinAttestationInclusionDelay = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowConfig
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MinAttestationInclusionDelay |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipConfig(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthConfig
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthConfig
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipConfig(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowConfig
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowConfig
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowConfig
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthConfig
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupConfig
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthConfig
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthConfig        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowConfig          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupConfig = fmt.Errorf("proto: unexpected end of group")
)
