// Code generated by protoc-gen-go. DO NOT EDIT.
// source: src/core/types.proto

package core

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type State struct {
	GenesisTime          uint64           `protobuf:"varint,1,opt,name=GenesisTime,proto3" json:"GenesisTime,omitempty"`
	CurrentEpoch         uint64           `protobuf:"varint,2,opt,name=CurrentEpoch,proto3" json:"CurrentEpoch,omitempty"`
	BlockRoots           []*EpochAndBytes `protobuf:"bytes,3,rep,name=BlockRoots,proto3" json:"BlockRoots,omitempty"`
	StateRoots           []*EpochAndBytes `protobuf:"bytes,4,rep,name=StateRoots,proto3" json:"StateRoots,omitempty"`
	Seeds                []*EpochAndBytes `protobuf:"bytes,5,rep,name=Seeds,proto3" json:"Seeds,omitempty"`
	BlockProducers       []*BlockProducer `protobuf:"bytes,6,rep,name=BlockProducers,proto3" json:"BlockProducers,omitempty"`
	Pools                []*Pool          `protobuf:"bytes,7,rep,name=Pools,proto3" json:"Pools,omitempty"`
	Slashings            []uint64         `protobuf:"varint,8,rep,packed,name=Slashings,proto3" json:"Slashings,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *State) Reset()         { *m = State{} }
func (m *State) String() string { return proto.CompactTextString(m) }
func (*State) ProtoMessage()    {}
func (*State) Descriptor() ([]byte, []int) {
	return fileDescriptor_05ece1b682f6d016, []int{0}
}

func (m *State) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_State.Unmarshal(m, b)
}
func (m *State) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_State.Marshal(b, m, deterministic)
}
func (m *State) XXX_Merge(src proto.Message) {
	xxx_messageInfo_State.Merge(m, src)
}
func (m *State) XXX_Size() int {
	return xxx_messageInfo_State.Size(m)
}
func (m *State) XXX_DiscardUnknown() {
	xxx_messageInfo_State.DiscardUnknown(m)
}

var xxx_messageInfo_State proto.InternalMessageInfo

func (m *State) GetGenesisTime() uint64 {
	if m != nil {
		return m.GenesisTime
	}
	return 0
}

func (m *State) GetCurrentEpoch() uint64 {
	if m != nil {
		return m.CurrentEpoch
	}
	return 0
}

func (m *State) GetBlockRoots() []*EpochAndBytes {
	if m != nil {
		return m.BlockRoots
	}
	return nil
}

func (m *State) GetStateRoots() []*EpochAndBytes {
	if m != nil {
		return m.StateRoots
	}
	return nil
}

func (m *State) GetSeeds() []*EpochAndBytes {
	if m != nil {
		return m.Seeds
	}
	return nil
}

func (m *State) GetBlockProducers() []*BlockProducer {
	if m != nil {
		return m.BlockProducers
	}
	return nil
}

func (m *State) GetPools() []*Pool {
	if m != nil {
		return m.Pools
	}
	return nil
}

func (m *State) GetSlashings() []uint64 {
	if m != nil {
		return m.Slashings
	}
	return nil
}

type BlockProducer struct {
	Id                   uint64   `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`
	PubKey               []byte   `protobuf:"bytes,2,opt,name=PubKey,proto3" json:"PubKey,omitempty"`
	Balance              uint64   `protobuf:"varint,3,opt,name=Balance,proto3" json:"Balance,omitempty"`
	Stake                uint64   `protobuf:"varint,4,opt,name=Stake,proto3" json:"Stake,omitempty"`
	Slashed              bool     `protobuf:"varint,5,opt,name=Slashed,proto3" json:"Slashed,omitempty"`
	Active               bool     `protobuf:"varint,6,opt,name=Active,proto3" json:"Active,omitempty"`
	ExitEpoch            uint64   `protobuf:"varint,7,opt,name=ExitEpoch,proto3" json:"ExitEpoch,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BlockProducer) Reset()         { *m = BlockProducer{} }
func (m *BlockProducer) String() string { return proto.CompactTextString(m) }
func (*BlockProducer) ProtoMessage()    {}
func (*BlockProducer) Descriptor() ([]byte, []int) {
	return fileDescriptor_05ece1b682f6d016, []int{1}
}

func (m *BlockProducer) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BlockProducer.Unmarshal(m, b)
}
func (m *BlockProducer) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BlockProducer.Marshal(b, m, deterministic)
}
func (m *BlockProducer) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BlockProducer.Merge(m, src)
}
func (m *BlockProducer) XXX_Size() int {
	return xxx_messageInfo_BlockProducer.Size(m)
}
func (m *BlockProducer) XXX_DiscardUnknown() {
	xxx_messageInfo_BlockProducer.DiscardUnknown(m)
}

var xxx_messageInfo_BlockProducer proto.InternalMessageInfo

func (m *BlockProducer) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *BlockProducer) GetPubKey() []byte {
	if m != nil {
		return m.PubKey
	}
	return nil
}

func (m *BlockProducer) GetBalance() uint64 {
	if m != nil {
		return m.Balance
	}
	return 0
}

func (m *BlockProducer) GetStake() uint64 {
	if m != nil {
		return m.Stake
	}
	return 0
}

func (m *BlockProducer) GetSlashed() bool {
	if m != nil {
		return m.Slashed
	}
	return false
}

func (m *BlockProducer) GetActive() bool {
	if m != nil {
		return m.Active
	}
	return false
}

func (m *BlockProducer) GetExitEpoch() uint64 {
	if m != nil {
		return m.ExitEpoch
	}
	return 0
}

type Pool struct {
	Id                   uint64   `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`
	Active               bool     `protobuf:"varint,2,opt,name=Active,proto3" json:"Active,omitempty"`
	PubKey               []byte   `protobuf:"bytes,3,opt,name=PubKey,proto3" json:"PubKey,omitempty"`
	SortedCommittee      []uint64 `protobuf:"varint,4,rep,packed,name=SortedCommittee,proto3" json:"SortedCommittee,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Pool) Reset()         { *m = Pool{} }
func (m *Pool) String() string { return proto.CompactTextString(m) }
func (*Pool) ProtoMessage()    {}
func (*Pool) Descriptor() ([]byte, []int) {
	return fileDescriptor_05ece1b682f6d016, []int{2}
}

func (m *Pool) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Pool.Unmarshal(m, b)
}
func (m *Pool) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Pool.Marshal(b, m, deterministic)
}
func (m *Pool) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Pool.Merge(m, src)
}
func (m *Pool) XXX_Size() int {
	return xxx_messageInfo_Pool.Size(m)
}
func (m *Pool) XXX_DiscardUnknown() {
	xxx_messageInfo_Pool.DiscardUnknown(m)
}

var xxx_messageInfo_Pool proto.InternalMessageInfo

func (m *Pool) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Pool) GetActive() bool {
	if m != nil {
		return m.Active
	}
	return false
}

func (m *Pool) GetPubKey() []byte {
	if m != nil {
		return m.PubKey
	}
	return nil
}

func (m *Pool) GetSortedCommittee() []uint64 {
	if m != nil {
		return m.SortedCommittee
	}
	return nil
}

type BeaconDuty struct {
	Type                 int32    `protobuf:"varint,1,opt,name=Type,proto3" json:"Type,omitempty"`
	Committee            uint64   `protobuf:"varint,2,opt,name=Committee,proto3" json:"Committee,omitempty"`
	Slot                 uint64   `protobuf:"varint,3,opt,name=Slot,proto3" json:"Slot,omitempty"`
	Finalized            bool     `protobuf:"varint,4,opt,name=Finalized,proto3" json:"Finalized,omitempty"`
	Participation        []byte   `protobuf:"bytes,5,opt,name=Participation,proto3" json:"Participation,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BeaconDuty) Reset()         { *m = BeaconDuty{} }
func (m *BeaconDuty) String() string { return proto.CompactTextString(m) }
func (*BeaconDuty) ProtoMessage()    {}
func (*BeaconDuty) Descriptor() ([]byte, []int) {
	return fileDescriptor_05ece1b682f6d016, []int{3}
}

func (m *BeaconDuty) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BeaconDuty.Unmarshal(m, b)
}
func (m *BeaconDuty) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BeaconDuty.Marshal(b, m, deterministic)
}
func (m *BeaconDuty) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BeaconDuty.Merge(m, src)
}
func (m *BeaconDuty) XXX_Size() int {
	return xxx_messageInfo_BeaconDuty.Size(m)
}
func (m *BeaconDuty) XXX_DiscardUnknown() {
	xxx_messageInfo_BeaconDuty.DiscardUnknown(m)
}

var xxx_messageInfo_BeaconDuty proto.InternalMessageInfo

func (m *BeaconDuty) GetType() int32 {
	if m != nil {
		return m.Type
	}
	return 0
}

func (m *BeaconDuty) GetCommittee() uint64 {
	if m != nil {
		return m.Committee
	}
	return 0
}

func (m *BeaconDuty) GetSlot() uint64 {
	if m != nil {
		return m.Slot
	}
	return 0
}

func (m *BeaconDuty) GetFinalized() bool {
	if m != nil {
		return m.Finalized
	}
	return false
}

func (m *BeaconDuty) GetParticipation() []byte {
	if m != nil {
		return m.Participation
	}
	return nil
}

type ExecutionSummary struct {
	PoolId               uint64        `protobuf:"varint,1,opt,name=PoolId,proto3" json:"PoolId,omitempty"`
	Epoch                uint64        `protobuf:"varint,2,opt,name=Epoch,proto3" json:"Epoch,omitempty"`
	Duties               []*BeaconDuty `protobuf:"bytes,3,rep,name=Duties,proto3" json:"Duties,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *ExecutionSummary) Reset()         { *m = ExecutionSummary{} }
func (m *ExecutionSummary) String() string { return proto.CompactTextString(m) }
func (*ExecutionSummary) ProtoMessage()    {}
func (*ExecutionSummary) Descriptor() ([]byte, []int) {
	return fileDescriptor_05ece1b682f6d016, []int{4}
}

func (m *ExecutionSummary) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ExecutionSummary.Unmarshal(m, b)
}
func (m *ExecutionSummary) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ExecutionSummary.Marshal(b, m, deterministic)
}
func (m *ExecutionSummary) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ExecutionSummary.Merge(m, src)
}
func (m *ExecutionSummary) XXX_Size() int {
	return xxx_messageInfo_ExecutionSummary.Size(m)
}
func (m *ExecutionSummary) XXX_DiscardUnknown() {
	xxx_messageInfo_ExecutionSummary.DiscardUnknown(m)
}

var xxx_messageInfo_ExecutionSummary proto.InternalMessageInfo

func (m *ExecutionSummary) GetPoolId() uint64 {
	if m != nil {
		return m.PoolId
	}
	return 0
}

func (m *ExecutionSummary) GetEpoch() uint64 {
	if m != nil {
		return m.Epoch
	}
	return 0
}

func (m *ExecutionSummary) GetDuties() []*BeaconDuty {
	if m != nil {
		return m.Duties
	}
	return nil
}

// A request struct for creating new pool credentials
// will trigger random selection of 128 executors to DKG new pool credentials and wait for deposit
//
// How it works?
// - A user sends 32 eth and create pool request
// - The first BP that sees it, will post a CreatePoolRequest with Status 0 and will nominate the next BP as the leader for the DKG
//   (the 128 DKG participants are deterministically selected as well)
// - If during the next Epoch the DKG is successful, the BP (which is also the DKG leader) posts a CreatePoolRequest with the same ID,
//   Status 1 and the created pub key
// - If the DKG is un-successful, the BP will post a CreatePoolRequest with the same ID, Status 3 and will nominate the next BP as leader
//
// A successful DKG will reward the leader and DKG participants
// A non-successful DKG will penalized the DKG participants
type CreateNewPoolRequest struct {
	Id                   uint64   `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`
	Status               int32    `protobuf:"varint,2,opt,name=Status,proto3" json:"Status,omitempty"`
	StartEpoch           uint64   `protobuf:"varint,3,opt,name=StartEpoch,proto3" json:"StartEpoch,omitempty"`
	EndEpoch             uint64   `protobuf:"varint,4,opt,name=EndEpoch,proto3" json:"EndEpoch,omitempty"`
	LeaderBlockProducer  uint64   `protobuf:"varint,5,opt,name=LeaderBlockProducer,proto3" json:"LeaderBlockProducer,omitempty"`
	CreatePubKey         []byte   `protobuf:"bytes,6,opt,name=CreatePubKey,proto3" json:"CreatePubKey,omitempty"`
	Participation        []byte   `protobuf:"bytes,7,opt,name=Participation,proto3" json:"Participation,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateNewPoolRequest) Reset()         { *m = CreateNewPoolRequest{} }
func (m *CreateNewPoolRequest) String() string { return proto.CompactTextString(m) }
func (*CreateNewPoolRequest) ProtoMessage()    {}
func (*CreateNewPoolRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_05ece1b682f6d016, []int{5}
}

func (m *CreateNewPoolRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateNewPoolRequest.Unmarshal(m, b)
}
func (m *CreateNewPoolRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateNewPoolRequest.Marshal(b, m, deterministic)
}
func (m *CreateNewPoolRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateNewPoolRequest.Merge(m, src)
}
func (m *CreateNewPoolRequest) XXX_Size() int {
	return xxx_messageInfo_CreateNewPoolRequest.Size(m)
}
func (m *CreateNewPoolRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateNewPoolRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateNewPoolRequest proto.InternalMessageInfo

func (m *CreateNewPoolRequest) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *CreateNewPoolRequest) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *CreateNewPoolRequest) GetStartEpoch() uint64 {
	if m != nil {
		return m.StartEpoch
	}
	return 0
}

func (m *CreateNewPoolRequest) GetEndEpoch() uint64 {
	if m != nil {
		return m.EndEpoch
	}
	return 0
}

func (m *CreateNewPoolRequest) GetLeaderBlockProducer() uint64 {
	if m != nil {
		return m.LeaderBlockProducer
	}
	return 0
}

func (m *CreateNewPoolRequest) GetCreatePubKey() []byte {
	if m != nil {
		return m.CreatePubKey
	}
	return nil
}

func (m *CreateNewPoolRequest) GetParticipation() []byte {
	if m != nil {
		return m.Participation
	}
	return nil
}

type BlockBody struct {
	Proposer             uint64                  `protobuf:"varint,1,opt,name=Proposer,proto3" json:"Proposer,omitempty"`
	Epoch                uint64                  `protobuf:"varint,2,opt,name=Epoch,proto3" json:"Epoch,omitempty"`
	ExecutionSummaries   []*ExecutionSummary     `protobuf:"bytes,3,rep,name=ExecutionSummaries,proto3" json:"ExecutionSummaries,omitempty"`
	NewPoolReq           []*CreateNewPoolRequest `protobuf:"bytes,4,rep,name=NewPoolReq,proto3" json:"NewPoolReq,omitempty"`
	StateRoot            []byte                  `protobuf:"bytes,5,opt,name=StateRoot,proto3" json:"StateRoot,omitempty"`
	ParentBlockRoot      []byte                  `protobuf:"bytes,6,opt,name=ParentBlockRoot,proto3" json:"ParentBlockRoot,omitempty"`
	Randao               []byte                  `protobuf:"bytes,7,opt,name=Randao,proto3" json:"Randao,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                `json:"-"`
	XXX_unrecognized     []byte                  `json:"-"`
	XXX_sizecache        int32                   `json:"-"`
}

func (m *BlockBody) Reset()         { *m = BlockBody{} }
func (m *BlockBody) String() string { return proto.CompactTextString(m) }
func (*BlockBody) ProtoMessage()    {}
func (*BlockBody) Descriptor() ([]byte, []int) {
	return fileDescriptor_05ece1b682f6d016, []int{6}
}

func (m *BlockBody) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BlockBody.Unmarshal(m, b)
}
func (m *BlockBody) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BlockBody.Marshal(b, m, deterministic)
}
func (m *BlockBody) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BlockBody.Merge(m, src)
}
func (m *BlockBody) XXX_Size() int {
	return xxx_messageInfo_BlockBody.Size(m)
}
func (m *BlockBody) XXX_DiscardUnknown() {
	xxx_messageInfo_BlockBody.DiscardUnknown(m)
}

var xxx_messageInfo_BlockBody proto.InternalMessageInfo

func (m *BlockBody) GetProposer() uint64 {
	if m != nil {
		return m.Proposer
	}
	return 0
}

func (m *BlockBody) GetEpoch() uint64 {
	if m != nil {
		return m.Epoch
	}
	return 0
}

func (m *BlockBody) GetExecutionSummaries() []*ExecutionSummary {
	if m != nil {
		return m.ExecutionSummaries
	}
	return nil
}

func (m *BlockBody) GetNewPoolReq() []*CreateNewPoolRequest {
	if m != nil {
		return m.NewPoolReq
	}
	return nil
}

func (m *BlockBody) GetStateRoot() []byte {
	if m != nil {
		return m.StateRoot
	}
	return nil
}

func (m *BlockBody) GetParentBlockRoot() []byte {
	if m != nil {
		return m.ParentBlockRoot
	}
	return nil
}

func (m *BlockBody) GetRandao() []byte {
	if m != nil {
		return m.Randao
	}
	return nil
}

type BlockHeader struct {
	BlockRoot            []byte   `protobuf:"bytes,1,opt,name=BlockRoot,proto3" json:"BlockRoot,omitempty"`
	Signature            []byte   `protobuf:"bytes,2,opt,name=Signature,proto3" json:"Signature,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BlockHeader) Reset()         { *m = BlockHeader{} }
func (m *BlockHeader) String() string { return proto.CompactTextString(m) }
func (*BlockHeader) ProtoMessage()    {}
func (*BlockHeader) Descriptor() ([]byte, []int) {
	return fileDescriptor_05ece1b682f6d016, []int{7}
}

func (m *BlockHeader) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BlockHeader.Unmarshal(m, b)
}
func (m *BlockHeader) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BlockHeader.Marshal(b, m, deterministic)
}
func (m *BlockHeader) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BlockHeader.Merge(m, src)
}
func (m *BlockHeader) XXX_Size() int {
	return xxx_messageInfo_BlockHeader.Size(m)
}
func (m *BlockHeader) XXX_DiscardUnknown() {
	xxx_messageInfo_BlockHeader.DiscardUnknown(m)
}

var xxx_messageInfo_BlockHeader proto.InternalMessageInfo

func (m *BlockHeader) GetBlockRoot() []byte {
	if m != nil {
		return m.BlockRoot
	}
	return nil
}

func (m *BlockHeader) GetSignature() []byte {
	if m != nil {
		return m.Signature
	}
	return nil
}

type EpochAndBytes struct {
	Epoch                uint64   `protobuf:"varint,1,opt,name=Epoch,proto3" json:"Epoch,omitempty"`
	Bytes                []byte   `protobuf:"bytes,2,opt,name=Bytes,proto3" json:"Bytes,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EpochAndBytes) Reset()         { *m = EpochAndBytes{} }
func (m *EpochAndBytes) String() string { return proto.CompactTextString(m) }
func (*EpochAndBytes) ProtoMessage()    {}
func (*EpochAndBytes) Descriptor() ([]byte, []int) {
	return fileDescriptor_05ece1b682f6d016, []int{8}
}

func (m *EpochAndBytes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EpochAndBytes.Unmarshal(m, b)
}
func (m *EpochAndBytes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EpochAndBytes.Marshal(b, m, deterministic)
}
func (m *EpochAndBytes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EpochAndBytes.Merge(m, src)
}
func (m *EpochAndBytes) XXX_Size() int {
	return xxx_messageInfo_EpochAndBytes.Size(m)
}
func (m *EpochAndBytes) XXX_DiscardUnknown() {
	xxx_messageInfo_EpochAndBytes.DiscardUnknown(m)
}

var xxx_messageInfo_EpochAndBytes proto.InternalMessageInfo

func (m *EpochAndBytes) GetEpoch() uint64 {
	if m != nil {
		return m.Epoch
	}
	return 0
}

func (m *EpochAndBytes) GetBytes() []byte {
	if m != nil {
		return m.Bytes
	}
	return nil
}

func init() {
	proto.RegisterType((*State)(nil), "state.State")
	proto.RegisterType((*BlockProducer)(nil), "state.BlockProducer")
	proto.RegisterType((*Pool)(nil), "state.Pool")
	proto.RegisterType((*BeaconDuty)(nil), "state.BeaconDuty")
	proto.RegisterType((*ExecutionSummary)(nil), "state.ExecutionSummary")
	proto.RegisterType((*CreateNewPoolRequest)(nil), "state.CreateNewPoolRequest")
	proto.RegisterType((*BlockBody)(nil), "state.BlockBody")
	proto.RegisterType((*BlockHeader)(nil), "state.BlockHeader")
	proto.RegisterType((*EpochAndBytes)(nil), "state.EpochAndBytes")
}

func init() {
	proto.RegisterFile("src/core/types.proto", fileDescriptor_05ece1b682f6d016)
}

var fileDescriptor_05ece1b682f6d016 = []byte{
	// 709 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x55, 0xcf, 0x6e, 0xd3, 0x4e,
	0x10, 0x96, 0x13, 0x3b, 0x49, 0x27, 0x6d, 0x7f, 0x3f, 0x96, 0x08, 0x2c, 0x40, 0x28, 0x58, 0x1c,
	0x02, 0x87, 0x14, 0x01, 0xb7, 0x72, 0x69, 0xda, 0x50, 0x2a, 0x10, 0x8a, 0x36, 0x3d, 0x71, 0xdb,
	0xda, 0xa3, 0xd6, 0x6a, 0xe2, 0x0d, 0xbb, 0x6b, 0xa8, 0x79, 0x10, 0x5e, 0x80, 0x87, 0xe0, 0x85,
	0x78, 0x06, 0xce, 0x68, 0xc7, 0x9b, 0x38, 0x0e, 0xa1, 0x37, 0x7f, 0xdf, 0xce, 0xbf, 0xfd, 0x66,
	0x76, 0x0c, 0x3d, 0xad, 0xe2, 0x83, 0x58, 0x2a, 0x3c, 0x30, 0xc5, 0x02, 0xf5, 0x70, 0xa1, 0xa4,
	0x91, 0x2c, 0xd0, 0x46, 0x18, 0x8c, 0x7e, 0x35, 0x20, 0x98, 0xda, 0x2f, 0xd6, 0x87, 0xee, 0x29,
	0x66, 0xa8, 0x53, 0x7d, 0x9e, 0xce, 0x31, 0xf4, 0xfa, 0xde, 0xc0, 0xe7, 0xeb, 0x14, 0x8b, 0x60,
	0xf7, 0x38, 0x57, 0x0a, 0x33, 0x33, 0x5e, 0xc8, 0xf8, 0x2a, 0x6c, 0x90, 0x49, 0x8d, 0x63, 0xaf,
	0x01, 0x46, 0x33, 0x19, 0x5f, 0x73, 0x29, 0x8d, 0x0e, 0x9b, 0xfd, 0xe6, 0xa0, 0xfb, 0xb2, 0x37,
	0xa4, 0x5c, 0x43, 0xb2, 0x38, 0xca, 0x92, 0x51, 0x61, 0x50, 0xf3, 0x35, 0x3b, 0xeb, 0x45, 0x45,
	0x94, 0x5e, 0xfe, 0x6d, 0x5e, 0x95, 0x1d, 0x7b, 0x0e, 0xc1, 0x14, 0x31, 0xd1, 0x61, 0x70, 0x8b,
	0x43, 0x69, 0xc2, 0xde, 0xc0, 0x3e, 0xe5, 0x9b, 0x28, 0x99, 0xe4, 0x31, 0x2a, 0x1d, 0xb6, 0x6a,
	0x4e, 0xb5, 0x43, 0xbe, 0x61, 0xcb, 0x9e, 0x40, 0x30, 0x91, 0x72, 0xa6, 0xc3, 0x36, 0x39, 0x75,
	0x9d, 0x93, 0xe5, 0x78, 0x79, 0xc2, 0x1e, 0xc1, 0xce, 0x74, 0x26, 0xf4, 0x55, 0x9a, 0x5d, 0xea,
	0xb0, 0xd3, 0x6f, 0x0e, 0x7c, 0x5e, 0x11, 0xd1, 0x4f, 0x0f, 0xf6, 0x6a, 0x31, 0xd9, 0x3e, 0x34,
	0xce, 0x12, 0xa7, 0x72, 0xe3, 0x2c, 0x61, 0xf7, 0xa0, 0x35, 0xc9, 0x2f, 0xde, 0x63, 0x41, 0xb2,
	0xee, 0x72, 0x87, 0x58, 0x08, 0xed, 0x91, 0x98, 0x89, 0x2c, 0xc6, 0xb0, 0x49, 0xc6, 0x4b, 0xc8,
	0x7a, 0xd4, 0xb9, 0x6b, 0x0c, 0x7d, 0xe2, 0x4b, 0x60, 0xed, 0x29, 0x2d, 0x26, 0x61, 0xd0, 0xf7,
	0x06, 0x1d, 0xbe, 0x84, 0x36, 0xc3, 0x51, 0x6c, 0xd2, 0x2f, 0x18, 0xb6, 0xe8, 0xc0, 0x21, 0x5b,
	0xf9, 0xf8, 0x26, 0x75, 0x3d, 0x6d, 0x53, 0xac, 0x8a, 0x88, 0x16, 0xe0, 0xdb, 0x0b, 0x6e, 0xab,
	0xd7, 0x45, 0x6b, 0xd4, 0xa2, 0x55, 0xf7, 0x68, 0xd6, 0xee, 0x31, 0x80, 0xff, 0xa6, 0x52, 0x19,
	0x4c, 0x8e, 0xe5, 0x7c, 0x9e, 0x1a, 0x83, 0x48, 0x7d, 0xf6, 0xf9, 0x26, 0x1d, 0x7d, 0xf7, 0x00,
	0x46, 0x28, 0x62, 0x99, 0x9d, 0xe4, 0xa6, 0x60, 0x0c, 0xfc, 0xf3, 0x62, 0x51, 0x0e, 0x64, 0xc0,
	0xe9, 0xdb, 0x96, 0x5c, 0x85, 0x29, 0xc7, 0xb0, 0x22, 0xac, 0xc7, 0x74, 0x26, 0x8d, 0xd3, 0x8b,
	0xbe, 0xad, 0xc7, 0xdb, 0x34, 0x13, 0xb3, 0xf4, 0x1b, 0x26, 0x24, 0x58, 0x87, 0x57, 0x04, 0x7b,
	0x0a, 0x7b, 0x13, 0xa1, 0x4c, 0x1a, 0xa7, 0x0b, 0x61, 0x52, 0x99, 0x91, 0x74, 0xbb, 0xbc, 0x4e,
	0x46, 0xd7, 0xf0, 0xff, 0xf8, 0x06, 0xe3, 0xdc, 0x82, 0x69, 0x3e, 0x9f, 0x0b, 0x55, 0xd0, 0x75,
	0xa5, 0x9c, 0xad, 0xa4, 0x71, 0xc8, 0x36, 0x67, 0xfd, 0x91, 0x94, 0x80, 0x3d, 0x83, 0xd6, 0x49,
	0x6e, 0x52, 0x5c, 0xbe, 0x8c, 0x3b, 0xcb, 0xe9, 0x5b, 0x5d, 0x97, 0x3b, 0x83, 0xe8, 0xb7, 0x07,
	0xbd, 0x63, 0x85, 0xc2, 0xe0, 0x47, 0xfc, 0x4a, 0x83, 0x86, 0x9f, 0x73, 0xd4, 0x66, 0x5b, 0x23,
	0xec, 0x9b, 0xc8, 0x35, 0xa5, 0x0a, 0xb8, 0x43, 0xec, 0x31, 0xbd, 0x29, 0xe5, 0xfa, 0x5a, 0x6a,
	0xb1, 0xc6, 0xb0, 0x07, 0xd0, 0x19, 0x67, 0x49, 0x79, 0x5a, 0x4e, 0xd0, 0x0a, 0xb3, 0x17, 0x70,
	0xf7, 0x03, 0x8a, 0x04, 0x55, 0x6d, 0x66, 0x49, 0x15, 0x9f, 0x6f, 0x3b, 0xa2, 0xdd, 0x40, 0xd5,
	0xba, 0xe6, 0xb7, 0x48, 0xc0, 0x1a, 0xf7, 0xb7, 0xca, 0xed, 0x6d, 0x2a, 0xff, 0x68, 0xc0, 0x0e,
	0xc5, 0x1e, 0xc9, 0xa4, 0xb0, 0x55, 0x4e, 0x94, 0x5c, 0x48, 0x8d, 0xca, 0xdd, 0x79, 0x85, 0xff,
	0xa1, 0xf1, 0x29, 0xb0, 0x8d, 0x2e, 0x55, 0x7a, 0xdf, 0x5f, 0xae, 0x88, 0x8d, 0x36, 0xf2, 0x2d,
	0x2e, 0xec, 0x10, 0xa0, 0x92, 0xde, 0x2d, 0xa5, 0x87, 0x2e, 0xc0, 0xb6, 0xce, 0xf0, 0x35, 0x73,
	0x5a, 0x07, 0xcb, 0x4d, 0xe5, 0xa6, 0xa9, 0x22, 0xec, 0x63, 0x98, 0x08, 0xbb, 0x34, 0x57, 0x3b,
	0xd0, 0x09, 0xb6, 0x49, 0xdb, 0xee, 0x72, 0x91, 0x25, 0x42, 0x3a, 0xb1, 0x1c, 0x8a, 0xce, 0xa0,
	0x4b, 0x46, 0xef, 0xa8, 0x17, 0x36, 0x5d, 0x15, 0xca, 0x2b, 0xd3, 0x55, 0x41, 0x6c, 0x31, 0xe9,
	0x65, 0x26, 0x4c, 0xae, 0xd0, 0xad, 0x97, 0x8a, 0x88, 0x0e, 0x61, 0xaf, 0xb6, 0x32, 0x2b, 0x5d,
	0xbd, 0x75, 0x5d, 0x7b, 0x10, 0xd0, 0xb1, 0x0b, 0x50, 0x82, 0x51, 0xe7, 0x53, 0x6b, 0x78, 0x68,
	0x7f, 0x2e, 0x17, 0x2d, 0xfa, 0xaf, 0xbc, 0xfa, 0x13, 0x00, 0x00, 0xff, 0xff, 0xa2, 0x5a, 0x3a,
	0xdb, 0x6f, 0x06, 0x00, 0x00,
}
