// Code generated by protoc-gen-go. DO NOT EDIT.
// source: src/core/types.proto

package core

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type State struct {
	// time
	GenesisTime  uint64 `protobuf:"varint,1,opt,name=GenesisTime,proto3" json:"GenesisTime,omitempty"`
	CurrentEpoch uint64 `protobuf:"varint,2,opt,name=CurrentEpoch,proto3" json:"CurrentEpoch,omitempty"`
	// past
	BlockRoots []*EpochAndBytes `protobuf:"bytes,3,rep,name=BlockRoots,proto3" json:"BlockRoots,omitempty"`
	StateRoots []*EpochAndBytes `protobuf:"bytes,4,rep,name=StateRoots,proto3" json:"StateRoots,omitempty"`
	Seeds      []*EpochAndBytes `protobuf:"bytes,5,rep,name=Seeds,proto3" json:"Seeds,omitempty"`
	// network
	BlockProducers       []*BlockProducer `protobuf:"bytes,6,rep,name=BlockProducers,proto3" json:"BlockProducers,omitempty"`
	Pools                []*Pool          `protobuf:"bytes,7,rep,name=Pools,proto3" json:"Pools,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *State) Reset()         { *m = State{} }
func (m *State) String() string { return proto.CompactTextString(m) }
func (*State) ProtoMessage()    {}
func (*State) Descriptor() ([]byte, []int) {
	return fileDescriptor_05ece1b682f6d016, []int{0}
}

func (m *State) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_State.Unmarshal(m, b)
}
func (m *State) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_State.Marshal(b, m, deterministic)
}
func (m *State) XXX_Merge(src proto.Message) {
	xxx_messageInfo_State.Merge(m, src)
}
func (m *State) XXX_Size() int {
	return xxx_messageInfo_State.Size(m)
}
func (m *State) XXX_DiscardUnknown() {
	xxx_messageInfo_State.DiscardUnknown(m)
}

var xxx_messageInfo_State proto.InternalMessageInfo

func (m *State) GetGenesisTime() uint64 {
	if m != nil {
		return m.GenesisTime
	}
	return 0
}

func (m *State) GetCurrentEpoch() uint64 {
	if m != nil {
		return m.CurrentEpoch
	}
	return 0
}

func (m *State) GetBlockRoots() []*EpochAndBytes {
	if m != nil {
		return m.BlockRoots
	}
	return nil
}

func (m *State) GetStateRoots() []*EpochAndBytes {
	if m != nil {
		return m.StateRoots
	}
	return nil
}

func (m *State) GetSeeds() []*EpochAndBytes {
	if m != nil {
		return m.Seeds
	}
	return nil
}

func (m *State) GetBlockProducers() []*BlockProducer {
	if m != nil {
		return m.BlockProducers
	}
	return nil
}

func (m *State) GetPools() []*Pool {
	if m != nil {
		return m.Pools
	}
	return nil
}

type BlockProducer struct {
	Id                   uint64   `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`
	PubKey               []byte   `protobuf:"bytes,2,opt,name=PubKey,proto3" json:"PubKey,omitempty"`
	CDTBalance           uint64   `protobuf:"varint,3,opt,name=CDTBalance,proto3" json:"CDTBalance,omitempty"`
	Stake                uint64   `protobuf:"varint,4,opt,name=Stake,proto3" json:"Stake,omitempty"`
	Slashed              bool     `protobuf:"varint,5,opt,name=Slashed,proto3" json:"Slashed,omitempty"`
	Active               bool     `protobuf:"varint,6,opt,name=Active,proto3" json:"Active,omitempty"`
	ExitEpoch            uint64   `protobuf:"varint,7,opt,name=ExitEpoch,proto3" json:"ExitEpoch,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BlockProducer) Reset()         { *m = BlockProducer{} }
func (m *BlockProducer) String() string { return proto.CompactTextString(m) }
func (*BlockProducer) ProtoMessage()    {}
func (*BlockProducer) Descriptor() ([]byte, []int) {
	return fileDescriptor_05ece1b682f6d016, []int{1}
}

func (m *BlockProducer) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BlockProducer.Unmarshal(m, b)
}
func (m *BlockProducer) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BlockProducer.Marshal(b, m, deterministic)
}
func (m *BlockProducer) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BlockProducer.Merge(m, src)
}
func (m *BlockProducer) XXX_Size() int {
	return xxx_messageInfo_BlockProducer.Size(m)
}
func (m *BlockProducer) XXX_DiscardUnknown() {
	xxx_messageInfo_BlockProducer.DiscardUnknown(m)
}

var xxx_messageInfo_BlockProducer proto.InternalMessageInfo

func (m *BlockProducer) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *BlockProducer) GetPubKey() []byte {
	if m != nil {
		return m.PubKey
	}
	return nil
}

func (m *BlockProducer) GetCDTBalance() uint64 {
	if m != nil {
		return m.CDTBalance
	}
	return 0
}

func (m *BlockProducer) GetStake() uint64 {
	if m != nil {
		return m.Stake
	}
	return 0
}

func (m *BlockProducer) GetSlashed() bool {
	if m != nil {
		return m.Slashed
	}
	return false
}

func (m *BlockProducer) GetActive() bool {
	if m != nil {
		return m.Active
	}
	return false
}

func (m *BlockProducer) GetExitEpoch() uint64 {
	if m != nil {
		return m.ExitEpoch
	}
	return 0
}

type Pool struct {
	Id                   uint64   `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`
	Active               bool     `protobuf:"varint,2,opt,name=Active,proto3" json:"Active,omitempty"`
	PubKey               []byte   `protobuf:"bytes,3,opt,name=PubKey,proto3" json:"PubKey,omitempty"`
	SortedCommittee      []uint64 `protobuf:"varint,4,rep,packed,name=SortedCommittee,proto3" json:"SortedCommittee,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Pool) Reset()         { *m = Pool{} }
func (m *Pool) String() string { return proto.CompactTextString(m) }
func (*Pool) ProtoMessage()    {}
func (*Pool) Descriptor() ([]byte, []int) {
	return fileDescriptor_05ece1b682f6d016, []int{2}
}

func (m *Pool) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Pool.Unmarshal(m, b)
}
func (m *Pool) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Pool.Marshal(b, m, deterministic)
}
func (m *Pool) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Pool.Merge(m, src)
}
func (m *Pool) XXX_Size() int {
	return xxx_messageInfo_Pool.Size(m)
}
func (m *Pool) XXX_DiscardUnknown() {
	xxx_messageInfo_Pool.DiscardUnknown(m)
}

var xxx_messageInfo_Pool proto.InternalMessageInfo

func (m *Pool) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Pool) GetActive() bool {
	if m != nil {
		return m.Active
	}
	return false
}

func (m *Pool) GetPubKey() []byte {
	if m != nil {
		return m.PubKey
	}
	return nil
}

func (m *Pool) GetSortedCommittee() []uint64 {
	if m != nil {
		return m.SortedCommittee
	}
	return nil
}

type BlockBody struct {
	Proposer             uint64                  `protobuf:"varint,1,opt,name=Proposer,proto3" json:"Proposer,omitempty"`
	Epoch                uint64                  `protobuf:"varint,2,opt,name=Epoch,proto3" json:"Epoch,omitempty"`
	ParentBlockRoot      []byte                  `protobuf:"bytes,3,opt,name=ParentBlockRoot,proto3" json:"ParentBlockRoot,omitempty"`
	Randao               []byte                  `protobuf:"bytes,4,opt,name=Randao,proto3" json:"Randao,omitempty"`
	NewPoolReq           []*CreateNewPoolRequest `protobuf:"bytes,5,rep,name=NewPoolReq,proto3" json:"NewPoolReq,omitempty"`
	Attestations         []*Attestation          `protobuf:"bytes,6,rep,name=attestations,proto3" json:"attestations,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                `json:"-"`
	XXX_unrecognized     []byte                  `json:"-"`
	XXX_sizecache        int32                   `json:"-"`
}

func (m *BlockBody) Reset()         { *m = BlockBody{} }
func (m *BlockBody) String() string { return proto.CompactTextString(m) }
func (*BlockBody) ProtoMessage()    {}
func (*BlockBody) Descriptor() ([]byte, []int) {
	return fileDescriptor_05ece1b682f6d016, []int{3}
}

func (m *BlockBody) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BlockBody.Unmarshal(m, b)
}
func (m *BlockBody) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BlockBody.Marshal(b, m, deterministic)
}
func (m *BlockBody) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BlockBody.Merge(m, src)
}
func (m *BlockBody) XXX_Size() int {
	return xxx_messageInfo_BlockBody.Size(m)
}
func (m *BlockBody) XXX_DiscardUnknown() {
	xxx_messageInfo_BlockBody.DiscardUnknown(m)
}

var xxx_messageInfo_BlockBody proto.InternalMessageInfo

func (m *BlockBody) GetProposer() uint64 {
	if m != nil {
		return m.Proposer
	}
	return 0
}

func (m *BlockBody) GetEpoch() uint64 {
	if m != nil {
		return m.Epoch
	}
	return 0
}

func (m *BlockBody) GetParentBlockRoot() []byte {
	if m != nil {
		return m.ParentBlockRoot
	}
	return nil
}

func (m *BlockBody) GetRandao() []byte {
	if m != nil {
		return m.Randao
	}
	return nil
}

func (m *BlockBody) GetNewPoolReq() []*CreateNewPoolRequest {
	if m != nil {
		return m.NewPoolReq
	}
	return nil
}

func (m *BlockBody) GetAttestations() []*Attestation {
	if m != nil {
		return m.Attestations
	}
	return nil
}

type BlockHeader struct {
	BlockRoot            []byte   `protobuf:"bytes,1,opt,name=BlockRoot,proto3" json:"BlockRoot,omitempty"`
	StateRoot            []byte   `protobuf:"bytes,2,opt,name=StateRoot,proto3" json:"StateRoot,omitempty"`
	Signature            []byte   `protobuf:"bytes,3,opt,name=Signature,proto3" json:"Signature,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BlockHeader) Reset()         { *m = BlockHeader{} }
func (m *BlockHeader) String() string { return proto.CompactTextString(m) }
func (*BlockHeader) ProtoMessage()    {}
func (*BlockHeader) Descriptor() ([]byte, []int) {
	return fileDescriptor_05ece1b682f6d016, []int{4}
}

func (m *BlockHeader) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BlockHeader.Unmarshal(m, b)
}
func (m *BlockHeader) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BlockHeader.Marshal(b, m, deterministic)
}
func (m *BlockHeader) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BlockHeader.Merge(m, src)
}
func (m *BlockHeader) XXX_Size() int {
	return xxx_messageInfo_BlockHeader.Size(m)
}
func (m *BlockHeader) XXX_DiscardUnknown() {
	xxx_messageInfo_BlockHeader.DiscardUnknown(m)
}

var xxx_messageInfo_BlockHeader proto.InternalMessageInfo

func (m *BlockHeader) GetBlockRoot() []byte {
	if m != nil {
		return m.BlockRoot
	}
	return nil
}

func (m *BlockHeader) GetStateRoot() []byte {
	if m != nil {
		return m.StateRoot
	}
	return nil
}

func (m *BlockHeader) GetSignature() []byte {
	if m != nil {
		return m.Signature
	}
	return nil
}

type Attestation struct {
	// A bitfield representation of validator indices that have voted exactly
	// the same vote and have been aggregated into this attestation.
	AggregationBits      []byte           `protobuf:"bytes,1,opt,name=aggregation_bits,json=aggregationBits,proto3" json:"aggregation_bits,omitempty"`
	Data                 *AttestationData `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	Signature            []byte           `protobuf:"bytes,3,opt,name=signature,proto3" json:"signature,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *Attestation) Reset()         { *m = Attestation{} }
func (m *Attestation) String() string { return proto.CompactTextString(m) }
func (*Attestation) ProtoMessage()    {}
func (*Attestation) Descriptor() ([]byte, []int) {
	return fileDescriptor_05ece1b682f6d016, []int{5}
}

func (m *Attestation) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Attestation.Unmarshal(m, b)
}
func (m *Attestation) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Attestation.Marshal(b, m, deterministic)
}
func (m *Attestation) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Attestation.Merge(m, src)
}
func (m *Attestation) XXX_Size() int {
	return xxx_messageInfo_Attestation.Size(m)
}
func (m *Attestation) XXX_DiscardUnknown() {
	xxx_messageInfo_Attestation.DiscardUnknown(m)
}

var xxx_messageInfo_Attestation proto.InternalMessageInfo

func (m *Attestation) GetAggregationBits() []byte {
	if m != nil {
		return m.AggregationBits
	}
	return nil
}

func (m *Attestation) GetData() *AttestationData {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *Attestation) GetSignature() []byte {
	if m != nil {
		return m.Signature
	}
	return nil
}

type AttestationData struct {
	// Slot of the attestation attesting for.
	Slot uint64 `protobuf:"varint,1,opt,name=slot,proto3" json:"slot,omitempty"`
	// The committee index that submitted this attestation.
	CommitteeIndex uint32 `protobuf:"varint,2,opt,name=committee_index,json=committeeIndex,proto3" json:"committee_index,omitempty"`
	// 32 byte root of the LMD GHOST block vote.
	BeaconBlockRoot []byte `protobuf:"bytes,3,opt,name=beacon_block_root,json=beaconBlockRoot,proto3" json:"beacon_block_root,omitempty"`
	// The most recent justified checkpoint in the beacon state
	Source *Checkpoint `protobuf:"bytes,4,opt,name=source,proto3" json:"source,omitempty"`
	// The checkpoint attempting to be justified for the current epoch and its epoch boundary block
	Target *Checkpoint `protobuf:"bytes,5,opt,name=target,proto3" json:"target,omitempty"`
	// The committees execution tasks.
	ExecutionSummaries   []*ExecutionSummary `protobuf:"bytes,6,rep,name=ExecutionSummaries,proto3" json:"ExecutionSummaries,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *AttestationData) Reset()         { *m = AttestationData{} }
func (m *AttestationData) String() string { return proto.CompactTextString(m) }
func (*AttestationData) ProtoMessage()    {}
func (*AttestationData) Descriptor() ([]byte, []int) {
	return fileDescriptor_05ece1b682f6d016, []int{6}
}

func (m *AttestationData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AttestationData.Unmarshal(m, b)
}
func (m *AttestationData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AttestationData.Marshal(b, m, deterministic)
}
func (m *AttestationData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AttestationData.Merge(m, src)
}
func (m *AttestationData) XXX_Size() int {
	return xxx_messageInfo_AttestationData.Size(m)
}
func (m *AttestationData) XXX_DiscardUnknown() {
	xxx_messageInfo_AttestationData.DiscardUnknown(m)
}

var xxx_messageInfo_AttestationData proto.InternalMessageInfo

func (m *AttestationData) GetSlot() uint64 {
	if m != nil {
		return m.Slot
	}
	return 0
}

func (m *AttestationData) GetCommitteeIndex() uint32 {
	if m != nil {
		return m.CommitteeIndex
	}
	return 0
}

func (m *AttestationData) GetBeaconBlockRoot() []byte {
	if m != nil {
		return m.BeaconBlockRoot
	}
	return nil
}

func (m *AttestationData) GetSource() *Checkpoint {
	if m != nil {
		return m.Source
	}
	return nil
}

func (m *AttestationData) GetTarget() *Checkpoint {
	if m != nil {
		return m.Target
	}
	return nil
}

func (m *AttestationData) GetExecutionSummaries() []*ExecutionSummary {
	if m != nil {
		return m.ExecutionSummaries
	}
	return nil
}

type BeaconDuty struct {
	Type                 int32    `protobuf:"varint,1,opt,name=Type,proto3" json:"Type,omitempty"`
	Committee            uint64   `protobuf:"varint,2,opt,name=Committee,proto3" json:"Committee,omitempty"`
	Slot                 uint64   `protobuf:"varint,3,opt,name=Slot,proto3" json:"Slot,omitempty"`
	Finalized            bool     `protobuf:"varint,4,opt,name=Finalized,proto3" json:"Finalized,omitempty"`
	Participation        []byte   `protobuf:"bytes,5,opt,name=Participation,proto3" json:"Participation,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BeaconDuty) Reset()         { *m = BeaconDuty{} }
func (m *BeaconDuty) String() string { return proto.CompactTextString(m) }
func (*BeaconDuty) ProtoMessage()    {}
func (*BeaconDuty) Descriptor() ([]byte, []int) {
	return fileDescriptor_05ece1b682f6d016, []int{7}
}

func (m *BeaconDuty) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BeaconDuty.Unmarshal(m, b)
}
func (m *BeaconDuty) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BeaconDuty.Marshal(b, m, deterministic)
}
func (m *BeaconDuty) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BeaconDuty.Merge(m, src)
}
func (m *BeaconDuty) XXX_Size() int {
	return xxx_messageInfo_BeaconDuty.Size(m)
}
func (m *BeaconDuty) XXX_DiscardUnknown() {
	xxx_messageInfo_BeaconDuty.DiscardUnknown(m)
}

var xxx_messageInfo_BeaconDuty proto.InternalMessageInfo

func (m *BeaconDuty) GetType() int32 {
	if m != nil {
		return m.Type
	}
	return 0
}

func (m *BeaconDuty) GetCommittee() uint64 {
	if m != nil {
		return m.Committee
	}
	return 0
}

func (m *BeaconDuty) GetSlot() uint64 {
	if m != nil {
		return m.Slot
	}
	return 0
}

func (m *BeaconDuty) GetFinalized() bool {
	if m != nil {
		return m.Finalized
	}
	return false
}

func (m *BeaconDuty) GetParticipation() []byte {
	if m != nil {
		return m.Participation
	}
	return nil
}

type ExecutionSummary struct {
	PoolId               uint64        `protobuf:"varint,1,opt,name=PoolId,proto3" json:"PoolId,omitempty"`
	Epoch                uint64        `protobuf:"varint,2,opt,name=Epoch,proto3" json:"Epoch,omitempty"`
	Duties               []*BeaconDuty `protobuf:"bytes,3,rep,name=Duties,proto3" json:"Duties,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *ExecutionSummary) Reset()         { *m = ExecutionSummary{} }
func (m *ExecutionSummary) String() string { return proto.CompactTextString(m) }
func (*ExecutionSummary) ProtoMessage()    {}
func (*ExecutionSummary) Descriptor() ([]byte, []int) {
	return fileDescriptor_05ece1b682f6d016, []int{8}
}

func (m *ExecutionSummary) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ExecutionSummary.Unmarshal(m, b)
}
func (m *ExecutionSummary) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ExecutionSummary.Marshal(b, m, deterministic)
}
func (m *ExecutionSummary) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ExecutionSummary.Merge(m, src)
}
func (m *ExecutionSummary) XXX_Size() int {
	return xxx_messageInfo_ExecutionSummary.Size(m)
}
func (m *ExecutionSummary) XXX_DiscardUnknown() {
	xxx_messageInfo_ExecutionSummary.DiscardUnknown(m)
}

var xxx_messageInfo_ExecutionSummary proto.InternalMessageInfo

func (m *ExecutionSummary) GetPoolId() uint64 {
	if m != nil {
		return m.PoolId
	}
	return 0
}

func (m *ExecutionSummary) GetEpoch() uint64 {
	if m != nil {
		return m.Epoch
	}
	return 0
}

func (m *ExecutionSummary) GetDuties() []*BeaconDuty {
	if m != nil {
		return m.Duties
	}
	return nil
}

type Checkpoint struct {
	// A checkpoint is every epoch's first slot. The goal of Casper FFG
	// is to link the check points together for justification and finalization.
	// Epoch the checkpoint references.
	Epoch uint64 `protobuf:"varint,1,opt,name=epoch,proto3" json:"epoch,omitempty"`
	// Block root of the checkpoint references.
	Root                 []byte   `protobuf:"bytes,2,opt,name=root,proto3" json:"root,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Checkpoint) Reset()         { *m = Checkpoint{} }
func (m *Checkpoint) String() string { return proto.CompactTextString(m) }
func (*Checkpoint) ProtoMessage()    {}
func (*Checkpoint) Descriptor() ([]byte, []int) {
	return fileDescriptor_05ece1b682f6d016, []int{9}
}

func (m *Checkpoint) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Checkpoint.Unmarshal(m, b)
}
func (m *Checkpoint) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Checkpoint.Marshal(b, m, deterministic)
}
func (m *Checkpoint) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Checkpoint.Merge(m, src)
}
func (m *Checkpoint) XXX_Size() int {
	return xxx_messageInfo_Checkpoint.Size(m)
}
func (m *Checkpoint) XXX_DiscardUnknown() {
	xxx_messageInfo_Checkpoint.DiscardUnknown(m)
}

var xxx_messageInfo_Checkpoint proto.InternalMessageInfo

func (m *Checkpoint) GetEpoch() uint64 {
	if m != nil {
		return m.Epoch
	}
	return 0
}

func (m *Checkpoint) GetRoot() []byte {
	if m != nil {
		return m.Root
	}
	return nil
}

type EpochAndBytes struct {
	Epoch                uint64   `protobuf:"varint,1,opt,name=Epoch,proto3" json:"Epoch,omitempty"`
	Bytes                []byte   `protobuf:"bytes,2,opt,name=Bytes,proto3" json:"Bytes,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EpochAndBytes) Reset()         { *m = EpochAndBytes{} }
func (m *EpochAndBytes) String() string { return proto.CompactTextString(m) }
func (*EpochAndBytes) ProtoMessage()    {}
func (*EpochAndBytes) Descriptor() ([]byte, []int) {
	return fileDescriptor_05ece1b682f6d016, []int{10}
}

func (m *EpochAndBytes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EpochAndBytes.Unmarshal(m, b)
}
func (m *EpochAndBytes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EpochAndBytes.Marshal(b, m, deterministic)
}
func (m *EpochAndBytes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EpochAndBytes.Merge(m, src)
}
func (m *EpochAndBytes) XXX_Size() int {
	return xxx_messageInfo_EpochAndBytes.Size(m)
}
func (m *EpochAndBytes) XXX_DiscardUnknown() {
	xxx_messageInfo_EpochAndBytes.DiscardUnknown(m)
}

var xxx_messageInfo_EpochAndBytes proto.InternalMessageInfo

func (m *EpochAndBytes) GetEpoch() uint64 {
	if m != nil {
		return m.Epoch
	}
	return 0
}

func (m *EpochAndBytes) GetBytes() []byte {
	if m != nil {
		return m.Bytes
	}
	return nil
}

func init() {
	proto.RegisterType((*State)(nil), "state.State")
	proto.RegisterType((*BlockProducer)(nil), "state.BlockProducer")
	proto.RegisterType((*Pool)(nil), "state.Pool")
	proto.RegisterType((*BlockBody)(nil), "state.BlockBody")
	proto.RegisterType((*BlockHeader)(nil), "state.BlockHeader")
	proto.RegisterType((*Attestation)(nil), "state.Attestation")
	proto.RegisterType((*AttestationData)(nil), "state.AttestationData")
	proto.RegisterType((*BeaconDuty)(nil), "state.BeaconDuty")
	proto.RegisterType((*ExecutionSummary)(nil), "state.ExecutionSummary")
	proto.RegisterType((*Checkpoint)(nil), "state.Checkpoint")
	proto.RegisterType((*EpochAndBytes)(nil), "state.EpochAndBytes")
}

func init() {
	proto.RegisterFile("src/core/types.proto", fileDescriptor_05ece1b682f6d016)
}

var fileDescriptor_05ece1b682f6d016 = []byte{
	// 816 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x55, 0x4f, 0x6f, 0xe4, 0x34,
	0x14, 0x57, 0xa6, 0xc9, 0xb4, 0xfb, 0x66, 0xda, 0xee, 0x5a, 0x55, 0x89, 0x16, 0x84, 0x4a, 0x84,
	0x44, 0xbb, 0x87, 0xae, 0x54, 0xd0, 0x5e, 0xca, 0xa5, 0xd3, 0x96, 0xa5, 0x42, 0x42, 0x23, 0x4f,
	0x4f, 0x5c, 0x2a, 0x37, 0x79, 0x9a, 0x5a, 0xcd, 0xc4, 0xc1, 0x76, 0xa0, 0xc3, 0x91, 0x0f, 0x81,
	0xc4, 0x87, 0xe1, 0xca, 0x27, 0xe2, 0x03, 0x20, 0xbf, 0x78, 0xc6, 0xc9, 0x50, 0x7a, 0xf3, 0xfb,
	0xbd, 0xdf, 0xf3, 0xfb, 0x6f, 0xc3, 0x81, 0xd1, 0xf9, 0xfb, 0x5c, 0x69, 0x7c, 0x6f, 0x97, 0x35,
	0x9a, 0xd3, 0x5a, 0x2b, 0xab, 0x58, 0x62, 0xac, 0xb0, 0xf8, 0xf6, 0x70, 0xad, 0x14, 0xb9, 0x95,
	0xaa, 0xf2, 0xea, 0xec, 0xef, 0x01, 0x24, 0x33, 0xc7, 0x60, 0x47, 0x30, 0xfa, 0x88, 0x15, 0x1a,
	0x69, 0x6e, 0xe5, 0x02, 0xd3, 0xe8, 0x28, 0x3a, 0x8e, 0x79, 0x17, 0x62, 0x19, 0x8c, 0x2f, 0x1b,
	0xad, 0xb1, 0xb2, 0xd7, 0xb5, 0xca, 0x1f, 0xd2, 0x01, 0x51, 0x7a, 0x18, 0xfb, 0x06, 0x60, 0x52,
	0xaa, 0xfc, 0x91, 0x2b, 0x65, 0x4d, 0xba, 0x75, 0xb4, 0x75, 0x3c, 0x3a, 0x3b, 0x38, 0xa5, 0x18,
	0x4e, 0x89, 0x71, 0x51, 0x15, 0x93, 0xa5, 0x45, 0xc3, 0x3b, 0x3c, 0x67, 0x45, 0x41, 0xb4, 0x56,
	0xf1, 0x4b, 0x56, 0x81, 0xc7, 0xde, 0x41, 0x32, 0x43, 0x2c, 0x4c, 0x9a, 0xbc, 0x60, 0xd0, 0x52,
	0xd8, 0xb7, 0xb0, 0x47, 0xfe, 0xa6, 0x5a, 0x15, 0x4d, 0x8e, 0xda, 0xa4, 0xc3, 0x9e, 0x51, 0x4f,
	0xc9, 0x37, 0xb8, 0xec, 0x0b, 0x48, 0xa6, 0x4a, 0x95, 0x26, 0xdd, 0x26, 0xa3, 0x91, 0x37, 0x72,
	0x18, 0x6f, 0x35, 0xd9, 0x5f, 0x11, 0xec, 0xf6, 0xac, 0xd8, 0x1e, 0x0c, 0x6e, 0x0a, 0x5f, 0xc7,
	0xc1, 0x4d, 0xc1, 0x0e, 0x61, 0x38, 0x6d, 0xee, 0x7f, 0xc0, 0x25, 0x15, 0x6e, 0xcc, 0xbd, 0xc4,
	0x3e, 0x07, 0xb8, 0xbc, 0xba, 0x9d, 0x88, 0x52, 0x54, 0x39, 0xa6, 0x5b, 0xc4, 0xef, 0x20, 0xec,
	0x80, 0x3a, 0xf4, 0x88, 0x69, 0x4c, 0xaa, 0x56, 0x60, 0x29, 0x6c, 0xcf, 0x4a, 0x61, 0x1e, 0xb0,
	0x48, 0x93, 0xa3, 0xe8, 0x78, 0x87, 0xaf, 0x44, 0xe7, 0xe7, 0x22, 0xb7, 0xf2, 0x17, 0x4c, 0x87,
	0xa4, 0xf0, 0x12, 0xfb, 0x0c, 0x5e, 0x5d, 0x3f, 0x49, 0xdf, 0xbb, 0x6d, 0xba, 0x2b, 0x00, 0x59,
	0x0d, 0xb1, 0x4b, 0xe4, 0xb9, 0xa8, 0xfd, 0x6d, 0x83, 0xde, 0x6d, 0x21, 0x9b, 0xad, 0x5e, 0x36,
	0xc7, 0xb0, 0x3f, 0x53, 0xda, 0x62, 0x71, 0xa9, 0x16, 0x0b, 0x69, 0x2d, 0x22, 0xf5, 0x33, 0xe6,
	0x9b, 0x70, 0xf6, 0x4f, 0x04, 0xaf, 0xa8, 0x62, 0x13, 0x55, 0x2c, 0xd9, 0x5b, 0xd8, 0x99, 0x6a,
	0x55, 0x2b, 0x83, 0xda, 0x7b, 0x5f, 0xcb, 0xae, 0x02, 0xdd, 0x89, 0x6b, 0x05, 0xe7, 0x69, 0x2a,
	0xdc, 0xe4, 0xad, 0x07, 0xc9, 0x87, 0xb2, 0x09, 0xbb, 0x58, 0xb9, 0xa8, 0x0a, 0xa1, 0xa8, 0x84,
	0x63, 0xee, 0x25, 0x76, 0x0e, 0xf0, 0x23, 0xfe, 0x4a, 0x5d, 0xc4, 0x9f, 0xfd, 0x14, 0x7d, 0xea,
	0x7b, 0x7b, 0xa9, 0x51, 0x58, 0x0c, 0xea, 0x06, 0x8d, 0xe5, 0x1d, 0x3a, 0xfb, 0x00, 0x63, 0x61,
	0x2d, 0x3a, 0xb6, 0xdb, 0x27, 0x3f, 0x4f, 0xcc, 0x9b, 0x5f, 0x04, 0x15, 0xef, 0xf1, 0xb2, 0x39,
	0x8c, 0x28, 0xb2, 0xef, 0x51, 0x14, 0xa8, 0x5d, 0x57, 0x42, 0xfc, 0x11, 0x85, 0x17, 0x00, 0xa7,
	0x5d, 0x0f, 0xbc, 0x1f, 0x9b, 0x00, 0x90, 0x56, 0xce, 0x2b, 0x61, 0x1b, 0x8d, 0x3e, 0xf7, 0x00,
	0x64, 0xbf, 0x47, 0x30, 0xea, 0x84, 0xc1, 0x4e, 0xe0, 0xb5, 0x98, 0xcf, 0x35, 0xce, 0x49, 0xbc,
	0xbb, 0x97, 0xd6, 0x78, 0x87, 0xfb, 0x1d, 0x7c, 0x22, 0x69, 0xb3, 0xe2, 0x42, 0x58, 0x41, 0x1e,
	0x47, 0x67, 0x87, 0xff, 0xcd, 0xe9, 0x4a, 0x58, 0xc1, 0x89, 0xe3, 0x82, 0x30, 0x9b, 0x41, 0xac,
	0x81, 0xec, 0xcf, 0x01, 0xec, 0x6f, 0xd8, 0x31, 0x06, 0xb1, 0x29, 0x7d, 0xb6, 0x31, 0xa7, 0x33,
	0xfb, 0x0a, 0xf6, 0xf3, 0xd5, 0x64, 0xdc, 0xc9, 0xaa, 0xc0, 0x27, 0x72, 0xbe, 0xcb, 0xf7, 0xd6,
	0xf0, 0x8d, 0x43, 0xd9, 0x3b, 0x78, 0x73, 0x8f, 0x22, 0x77, 0x09, 0xb8, 0x2a, 0xdd, 0xe9, 0x4e,
	0xdf, 0x5b, 0x45, 0xa8, 0xde, 0x09, 0x0c, 0x8d, 0x6a, 0x74, 0xde, 0xae, 0xce, 0xe8, 0xec, 0xcd,
	0xaa, 0xb7, 0x0f, 0x98, 0x3f, 0xd6, 0x4a, 0x56, 0x96, 0x7b, 0x82, 0xa3, 0x5a, 0xa1, 0xe7, 0x68,
	0x69, 0x9b, 0x9e, 0xa7, 0xb6, 0x04, 0xf6, 0x11, 0xd8, 0xf5, 0x13, 0xe6, 0x8d, 0xcb, 0x67, 0xd6,
	0x2c, 0x16, 0x42, 0x4b, 0x5c, 0xb5, 0xff, 0x93, 0xd5, 0x1b, 0xd4, 0x27, 0x2c, 0xf9, 0x33, 0x26,
	0xd9, 0x1f, 0x11, 0xc0, 0x84, 0x42, 0xbe, 0x6a, 0xec, 0xd2, 0x95, 0xe5, 0x76, 0x59, 0xb7, 0x2f,
	0x6f, 0xc2, 0xe9, 0xec, 0x8a, 0x1b, 0xf6, 0xa8, 0x9d, 0xfe, 0x00, 0x38, 0x8b, 0x59, 0xe9, 0xd3,
	0x8f, 0x39, 0x9d, 0x9d, 0xc5, 0x77, 0xb2, 0x12, 0xa5, 0xfc, 0x0d, 0x0b, 0x4a, 0x7b, 0x87, 0x07,
	0x80, 0x7d, 0x09, 0xbb, 0x53, 0xa1, 0xad, 0xcc, 0x65, 0x4d, 0xfd, 0xa0, 0x6c, 0xc7, 0xbc, 0x0f,
	0x66, 0x8f, 0xf0, 0x7a, 0x33, 0x01, 0xda, 0x77, 0xa5, 0xca, 0xf5, 0xdb, 0xe0, 0xa5, 0xff, 0xd9,
	0xcd, 0x13, 0x18, 0x5e, 0x35, 0xd6, 0xd5, 0xa5, 0xfd, 0x02, 0x56, 0xe5, 0x0c, 0xe9, 0x72, 0x4f,
	0xc8, 0x3e, 0x00, 0x84, 0x22, 0xbb, 0xeb, 0x90, 0xae, 0x6b, 0xbd, 0xb4, 0x82, 0x4b, 0x54, 0x87,
	0x0d, 0xa0, 0x73, 0x76, 0x0e, 0xbb, 0xbd, 0x97, 0x3e, 0x44, 0x12, 0x75, 0x23, 0x39, 0x80, 0x84,
	0xd4, 0xde, 0xb6, 0x15, 0x26, 0x3b, 0x3f, 0x0d, 0x4f, 0xcf, 0xdd, 0x77, 0x78, 0x3f, 0xa4, 0x7f,
	0xf0, 0xeb, 0x7f, 0x03, 0x00, 0x00, 0xff, 0xff, 0x5c, 0x3e, 0x58, 0xfb, 0x3e, 0x07, 0x00, 0x00,
}
