// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.24.0
// 	protoc        v3.11.4
// source: src/core/types.proto

package core

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type BeaconDuty_DutyType int32

const (
	BeaconDuty_Attestation BeaconDuty_DutyType = 0
	BeaconDuty_Proposal    BeaconDuty_DutyType = 1
	BeaconDuty_Aggregation BeaconDuty_DutyType = 2
)

// Enum value maps for BeaconDuty_DutyType.
var (
	BeaconDuty_DutyType_name = map[int32]string{
		0: "Attestation",
		1: "Proposal",
		2: "Aggregation",
	}
	BeaconDuty_DutyType_value = map[string]int32{
		"Attestation": 0,
		"Proposal":    1,
		"Aggregation": 2,
	}
)

func (x BeaconDuty_DutyType) Enum() *BeaconDuty_DutyType {
	p := new(BeaconDuty_DutyType)
	*p = x
	return p
}

func (x BeaconDuty_DutyType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (BeaconDuty_DutyType) Descriptor() protoreflect.EnumDescriptor {
	return file_src_core_types_proto_enumTypes[0].Descriptor()
}

func (BeaconDuty_DutyType) Type() protoreflect.EnumType {
	return &file_src_core_types_proto_enumTypes[0]
}

func (x BeaconDuty_DutyType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use BeaconDuty_DutyType.Descriptor instead.
func (BeaconDuty_DutyType) EnumDescriptor() ([]byte, []int) {
	return file_src_core_types_proto_rawDescGZIP(), []int{3, 0}
}

type CreateNewPoolRequest_NewPoolStatus int32

const (
	CreateNewPoolRequest_Started      CreateNewPoolRequest_NewPoolStatus = 0
	CreateNewPoolRequest_Completed    CreateNewPoolRequest_NewPoolStatus = 1
	CreateNewPoolRequest_Unsuccessful CreateNewPoolRequest_NewPoolStatus = 2
)

// Enum value maps for CreateNewPoolRequest_NewPoolStatus.
var (
	CreateNewPoolRequest_NewPoolStatus_name = map[int32]string{
		0: "Started",
		1: "Completed",
		2: "Unsuccessful",
	}
	CreateNewPoolRequest_NewPoolStatus_value = map[string]int32{
		"Started":      0,
		"Completed":    1,
		"Unsuccessful": 2,
	}
)

func (x CreateNewPoolRequest_NewPoolStatus) Enum() *CreateNewPoolRequest_NewPoolStatus {
	p := new(CreateNewPoolRequest_NewPoolStatus)
	*p = x
	return p
}

func (x CreateNewPoolRequest_NewPoolStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CreateNewPoolRequest_NewPoolStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_src_core_types_proto_enumTypes[1].Descriptor()
}

func (CreateNewPoolRequest_NewPoolStatus) Type() protoreflect.EnumType {
	return &file_src_core_types_proto_enumTypes[1]
}

func (x CreateNewPoolRequest_NewPoolStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CreateNewPoolRequest_NewPoolStatus.Descriptor instead.
func (CreateNewPoolRequest_NewPoolStatus) EnumDescriptor() ([]byte, []int) {
	return file_src_core_types_proto_rawDescGZIP(), []int{5, 0}
}

type State struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GenesisTime    uint64           `protobuf:"varint,1,opt,name=GenesisTime,proto3" json:"GenesisTime,omitempty"`
	CurrentEpoch   uint64           `protobuf:"varint,2,opt,name=CurrentEpoch,proto3" json:"CurrentEpoch,omitempty"`
	BlockRoots     [][]byte         `protobuf:"bytes,3,rep,name=BlockRoots,proto3" json:"BlockRoots,omitempty"`
	StateRoots     [][]byte         `protobuf:"bytes,4,rep,name=StateRoots,proto3" json:"StateRoots,omitempty"`
	Seeds          [][]byte         `protobuf:"bytes,5,rep,name=Seeds,proto3" json:"Seeds,omitempty"`
	BlockProducers []*BlockProducer `protobuf:"bytes,6,rep,name=BlockProducers,proto3" json:"BlockProducers,omitempty"`
	Pools          []*Pool          `protobuf:"bytes,7,rep,name=Pools,proto3" json:"Pools,omitempty"`
	Slashings      []uint64         `protobuf:"varint,8,rep,packed,name=Slashings,proto3" json:"Slashings,omitempty"`
}

func (x *State) Reset() {
	*x = State{}
	if protoimpl.UnsafeEnabled {
		mi := &file_src_core_types_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *State) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*State) ProtoMessage() {}

func (x *State) ProtoReflect() protoreflect.Message {
	mi := &file_src_core_types_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use State.ProtoReflect.Descriptor instead.
func (*State) Descriptor() ([]byte, []int) {
	return file_src_core_types_proto_rawDescGZIP(), []int{0}
}

func (x *State) GetGenesisTime() uint64 {
	if x != nil {
		return x.GenesisTime
	}
	return 0
}

func (x *State) GetCurrentEpoch() uint64 {
	if x != nil {
		return x.CurrentEpoch
	}
	return 0
}

func (x *State) GetBlockRoots() [][]byte {
	if x != nil {
		return x.BlockRoots
	}
	return nil
}

func (x *State) GetStateRoots() [][]byte {
	if x != nil {
		return x.StateRoots
	}
	return nil
}

func (x *State) GetSeeds() [][]byte {
	if x != nil {
		return x.Seeds
	}
	return nil
}

func (x *State) GetBlockProducers() []*BlockProducer {
	if x != nil {
		return x.BlockProducers
	}
	return nil
}

func (x *State) GetPools() []*Pool {
	if x != nil {
		return x.Pools
	}
	return nil
}

func (x *State) GetSlashings() []uint64 {
	if x != nil {
		return x.Slashings
	}
	return nil
}

type BlockProducer struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id        uint64 `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`
	PubKey    []byte `protobuf:"bytes,2,opt,name=PubKey,proto3" json:"PubKey,omitempty"`
	Balance   uint64 `protobuf:"varint,3,opt,name=Balance,proto3" json:"Balance,omitempty"`
	Stake     uint64 `protobuf:"varint,4,opt,name=Stake,proto3" json:"Stake,omitempty"`
	Slashed   bool   `protobuf:"varint,5,opt,name=Slashed,proto3" json:"Slashed,omitempty"`
	Active    bool   `protobuf:"varint,6,opt,name=Active,proto3" json:"Active,omitempty"`
	ExitEpoch uint64 `protobuf:"varint,7,opt,name=ExitEpoch,proto3" json:"ExitEpoch,omitempty"`
}

func (x *BlockProducer) Reset() {
	*x = BlockProducer{}
	if protoimpl.UnsafeEnabled {
		mi := &file_src_core_types_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BlockProducer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlockProducer) ProtoMessage() {}

func (x *BlockProducer) ProtoReflect() protoreflect.Message {
	mi := &file_src_core_types_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlockProducer.ProtoReflect.Descriptor instead.
func (*BlockProducer) Descriptor() ([]byte, []int) {
	return file_src_core_types_proto_rawDescGZIP(), []int{1}
}

func (x *BlockProducer) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *BlockProducer) GetPubKey() []byte {
	if x != nil {
		return x.PubKey
	}
	return nil
}

func (x *BlockProducer) GetBalance() uint64 {
	if x != nil {
		return x.Balance
	}
	return 0
}

func (x *BlockProducer) GetStake() uint64 {
	if x != nil {
		return x.Stake
	}
	return 0
}

func (x *BlockProducer) GetSlashed() bool {
	if x != nil {
		return x.Slashed
	}
	return false
}

func (x *BlockProducer) GetActive() bool {
	if x != nil {
		return x.Active
	}
	return false
}

func (x *BlockProducer) GetExitEpoch() uint64 {
	if x != nil {
		return x.ExitEpoch
	}
	return 0
}

type Pool struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id              uint64   `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`
	Active          bool     `protobuf:"varint,2,opt,name=Active,proto3" json:"Active,omitempty"`
	PubKey          []byte   `protobuf:"bytes,3,opt,name=PubKey,proto3" json:"PubKey,omitempty"`
	SortedCommittee []uint64 `protobuf:"varint,4,rep,packed,name=SortedCommittee,proto3" json:"SortedCommittee,omitempty"`
}

func (x *Pool) Reset() {
	*x = Pool{}
	if protoimpl.UnsafeEnabled {
		mi := &file_src_core_types_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Pool) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Pool) ProtoMessage() {}

func (x *Pool) ProtoReflect() protoreflect.Message {
	mi := &file_src_core_types_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Pool.ProtoReflect.Descriptor instead.
func (*Pool) Descriptor() ([]byte, []int) {
	return file_src_core_types_proto_rawDescGZIP(), []int{2}
}

func (x *Pool) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Pool) GetActive() bool {
	if x != nil {
		return x.Active
	}
	return false
}

func (x *Pool) GetPubKey() []byte {
	if x != nil {
		return x.PubKey
	}
	return nil
}

func (x *Pool) GetSortedCommittee() []uint64 {
	if x != nil {
		return x.SortedCommittee
	}
	return nil
}

type BeaconDuty struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type          BeaconDuty_DutyType `protobuf:"varint,1,opt,name=Type,proto3,enum=state.BeaconDuty_DutyType" json:"Type,omitempty"`
	Committee     uint64              `protobuf:"varint,2,opt,name=Committee,proto3" json:"Committee,omitempty"`
	Slott         uint64              `protobuf:"varint,3,opt,name=Slott,proto3" json:"Slott,omitempty"`
	Finalized     bool                `protobuf:"varint,4,opt,name=Finalized,proto3" json:"Finalized,omitempty"`
	Participation []byte              `protobuf:"bytes,5,opt,name=Participation,proto3" json:"Participation,omitempty"` // 128 bit of the executors (by order) which executed this duty
}

func (x *BeaconDuty) Reset() {
	*x = BeaconDuty{}
	if protoimpl.UnsafeEnabled {
		mi := &file_src_core_types_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BeaconDuty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BeaconDuty) ProtoMessage() {}

func (x *BeaconDuty) ProtoReflect() protoreflect.Message {
	mi := &file_src_core_types_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BeaconDuty.ProtoReflect.Descriptor instead.
func (*BeaconDuty) Descriptor() ([]byte, []int) {
	return file_src_core_types_proto_rawDescGZIP(), []int{3}
}

func (x *BeaconDuty) GetType() BeaconDuty_DutyType {
	if x != nil {
		return x.Type
	}
	return BeaconDuty_Attestation
}

func (x *BeaconDuty) GetCommittee() uint64 {
	if x != nil {
		return x.Committee
	}
	return 0
}

func (x *BeaconDuty) GetSlott() uint64 {
	if x != nil {
		return x.Slott
	}
	return 0
}

func (x *BeaconDuty) GetFinalized() bool {
	if x != nil {
		return x.Finalized
	}
	return false
}

func (x *BeaconDuty) GetParticipation() []byte {
	if x != nil {
		return x.Participation
	}
	return nil
}

type ExecutionSummary struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PoolId uint64        `protobuf:"varint,1,opt,name=PoolId,proto3" json:"PoolId,omitempty"`
	Epoch  uint64        `protobuf:"varint,2,opt,name=Epoch,proto3" json:"Epoch,omitempty"`
	Duties []*BeaconDuty `protobuf:"bytes,3,rep,name=Duties,proto3" json:"Duties,omitempty"`
}

func (x *ExecutionSummary) Reset() {
	*x = ExecutionSummary{}
	if protoimpl.UnsafeEnabled {
		mi := &file_src_core_types_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ExecutionSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecutionSummary) ProtoMessage() {}

func (x *ExecutionSummary) ProtoReflect() protoreflect.Message {
	mi := &file_src_core_types_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecutionSummary.ProtoReflect.Descriptor instead.
func (*ExecutionSummary) Descriptor() ([]byte, []int) {
	return file_src_core_types_proto_rawDescGZIP(), []int{4}
}

func (x *ExecutionSummary) GetPoolId() uint64 {
	if x != nil {
		return x.PoolId
	}
	return 0
}

func (x *ExecutionSummary) GetEpoch() uint64 {
	if x != nil {
		return x.Epoch
	}
	return 0
}

func (x *ExecutionSummary) GetDuties() []*BeaconDuty {
	if x != nil {
		return x.Duties
	}
	return nil
}

// A request struct for creating new pool credentials
// will trigger random selection of 128 executors to DKG new pool credentials and wait for deposit
//
// How it works?
// - A user sends 32 eth and create pool request
// - The first BP that sees it, will post a CreatePoolRequest with Status 0 and will nominate the next BP as the leader for the DKG
//   (the 128 DKG participants are deterministically selected as well)
// - If during the next Epoch the DKG is successful, the BP (which is also the DKG leader) posts a CreatePoolRequest with the same ID,
//   Status 1 and the created pub key
// - If the DKG is un-successful, the BP will post a CreatePoolRequest with the same ID, Status 3 and will nominate the next BP as leader
//
// A successful DKG will reward the leader and DKG participants
// A non-successful DKG will penalized the DKG participants
type CreateNewPoolRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id                  uint64                             `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"` // primary key
	Status              CreateNewPoolRequest_NewPoolStatus `protobuf:"varint,2,opt,name=Status,proto3,enum=state.CreateNewPoolRequest_NewPoolStatus" json:"Status,omitempty"`
	StartEpoch          uint64                             `protobuf:"varint,3,opt,name=StartEpoch,proto3" json:"StartEpoch,omitempty"`                   // epoch in which the request was included
	EndEpoch            uint64                             `protobuf:"varint,4,opt,name=EndEpoch,proto3" json:"EndEpoch,omitempty"`                       // max epoch for the request to be completed or failed
	LeaderBlockProducer uint64                             `protobuf:"varint,5,opt,name=LeaderBlockProducer,proto3" json:"LeaderBlockProducer,omitempty"` // should be the BP proposer of next block after which this request was included in.
	CreatePubKey        []byte                             `protobuf:"bytes,6,opt,name=CreatePubKey,proto3" json:"CreatePubKey,omitempty"`                // populated after DKG is successful
	Participation       []byte                             `protobuf:"bytes,7,opt,name=Participation,proto3" json:"Participation,omitempty"`              // 128 bit of the executors (by order) which executed this duty
}

func (x *CreateNewPoolRequest) Reset() {
	*x = CreateNewPoolRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_src_core_types_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateNewPoolRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateNewPoolRequest) ProtoMessage() {}

func (x *CreateNewPoolRequest) ProtoReflect() protoreflect.Message {
	mi := &file_src_core_types_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateNewPoolRequest.ProtoReflect.Descriptor instead.
func (*CreateNewPoolRequest) Descriptor() ([]byte, []int) {
	return file_src_core_types_proto_rawDescGZIP(), []int{5}
}

func (x *CreateNewPoolRequest) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *CreateNewPoolRequest) GetStatus() CreateNewPoolRequest_NewPoolStatus {
	if x != nil {
		return x.Status
	}
	return CreateNewPoolRequest_Started
}

func (x *CreateNewPoolRequest) GetStartEpoch() uint64 {
	if x != nil {
		return x.StartEpoch
	}
	return 0
}

func (x *CreateNewPoolRequest) GetEndEpoch() uint64 {
	if x != nil {
		return x.EndEpoch
	}
	return 0
}

func (x *CreateNewPoolRequest) GetLeaderBlockProducer() uint64 {
	if x != nil {
		return x.LeaderBlockProducer
	}
	return 0
}

func (x *CreateNewPoolRequest) GetCreatePubKey() []byte {
	if x != nil {
		return x.CreatePubKey
	}
	return nil
}

func (x *CreateNewPoolRequest) GetParticipation() []byte {
	if x != nil {
		return x.Participation
	}
	return nil
}

type BlockBody struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Proposer           uint64                  `protobuf:"varint,1,opt,name=Proposer,proto3" json:"Proposer,omitempty"`
	Epoch              uint64                  `protobuf:"varint,2,opt,name=Epoch,proto3" json:"Epoch,omitempty"`
	ExecutionSummaries []*ExecutionSummary     `protobuf:"bytes,3,rep,name=ExecutionSummaries,proto3" json:"ExecutionSummaries,omitempty"`
	NewPoolReq         []*CreateNewPoolRequest `protobuf:"bytes,4,rep,name=NewPoolReq,proto3" json:"NewPoolReq,omitempty"`
	StateRoot          [][]byte                `protobuf:"bytes,5,rep,name=StateRoot,proto3" json:"StateRoot,omitempty"`
	ParentBlockRoot    [][]byte                `protobuf:"bytes,6,rep,name=ParentBlockRoot,proto3" json:"ParentBlockRoot,omitempty"`
}

func (x *BlockBody) Reset() {
	*x = BlockBody{}
	if protoimpl.UnsafeEnabled {
		mi := &file_src_core_types_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BlockBody) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlockBody) ProtoMessage() {}

func (x *BlockBody) ProtoReflect() protoreflect.Message {
	mi := &file_src_core_types_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlockBody.ProtoReflect.Descriptor instead.
func (*BlockBody) Descriptor() ([]byte, []int) {
	return file_src_core_types_proto_rawDescGZIP(), []int{6}
}

func (x *BlockBody) GetProposer() uint64 {
	if x != nil {
		return x.Proposer
	}
	return 0
}

func (x *BlockBody) GetEpoch() uint64 {
	if x != nil {
		return x.Epoch
	}
	return 0
}

func (x *BlockBody) GetExecutionSummaries() []*ExecutionSummary {
	if x != nil {
		return x.ExecutionSummaries
	}
	return nil
}

func (x *BlockBody) GetNewPoolReq() []*CreateNewPoolRequest {
	if x != nil {
		return x.NewPoolReq
	}
	return nil
}

func (x *BlockBody) GetStateRoot() [][]byte {
	if x != nil {
		return x.StateRoot
	}
	return nil
}

func (x *BlockBody) GetParentBlockRoot() [][]byte {
	if x != nil {
		return x.ParentBlockRoot
	}
	return nil
}

type BlockHeader struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BlockRoot []byte `protobuf:"bytes,1,opt,name=BlockRoot,proto3" json:"BlockRoot,omitempty"`
	Signature []byte `protobuf:"bytes,2,opt,name=Signature,proto3" json:"Signature,omitempty"`
}

func (x *BlockHeader) Reset() {
	*x = BlockHeader{}
	if protoimpl.UnsafeEnabled {
		mi := &file_src_core_types_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BlockHeader) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlockHeader) ProtoMessage() {}

func (x *BlockHeader) ProtoReflect() protoreflect.Message {
	mi := &file_src_core_types_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlockHeader.ProtoReflect.Descriptor instead.
func (*BlockHeader) Descriptor() ([]byte, []int) {
	return file_src_core_types_proto_rawDescGZIP(), []int{7}
}

func (x *BlockHeader) GetBlockRoot() []byte {
	if x != nil {
		return x.BlockRoot
	}
	return nil
}

func (x *BlockHeader) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

var File_src_core_types_proto protoreflect.FileDescriptor

var file_src_core_types_proto_rawDesc = []byte{
	0x0a, 0x14, 0x73, 0x72, 0x63, 0x2f, 0x63, 0x6f, 0x72, 0x65, 0x2f, 0x74, 0x79, 0x70, 0x65, 0x73,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x22, 0xa2, 0x02,
	0x0a, 0x05, 0x53, 0x74, 0x61, 0x74, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x47, 0x65, 0x6e, 0x65, 0x73,
	0x69, 0x73, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0b, 0x47, 0x65,
	0x6e, 0x65, 0x73, 0x69, 0x73, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x22, 0x0a, 0x0c, 0x43, 0x75, 0x72,
	0x72, 0x65, 0x6e, 0x74, 0x45, 0x70, 0x6f, 0x63, 0x68, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52,
	0x0c, 0x43, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x74, 0x45, 0x70, 0x6f, 0x63, 0x68, 0x12, 0x1e, 0x0a,
	0x0a, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x52, 0x6f, 0x6f, 0x74, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28,
	0x0c, 0x52, 0x0a, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x52, 0x6f, 0x6f, 0x74, 0x73, 0x12, 0x1e, 0x0a,
	0x0a, 0x53, 0x74, 0x61, 0x74, 0x65, 0x52, 0x6f, 0x6f, 0x74, 0x73, 0x18, 0x04, 0x20, 0x03, 0x28,
	0x0c, 0x52, 0x0a, 0x53, 0x74, 0x61, 0x74, 0x65, 0x52, 0x6f, 0x6f, 0x74, 0x73, 0x12, 0x14, 0x0a,
	0x05, 0x53, 0x65, 0x65, 0x64, 0x73, 0x18, 0x05, 0x20, 0x03, 0x28, 0x0c, 0x52, 0x05, 0x53, 0x65,
	0x65, 0x64, 0x73, 0x12, 0x3c, 0x0a, 0x0e, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x50, 0x72, 0x6f, 0x64,
	0x75, 0x63, 0x65, 0x72, 0x73, 0x18, 0x06, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x73, 0x74,
	0x61, 0x74, 0x65, 0x2e, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x65,
	0x72, 0x52, 0x0e, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x65, 0x72,
	0x73, 0x12, 0x21, 0x0a, 0x05, 0x50, 0x6f, 0x6f, 0x6c, 0x73, 0x18, 0x07, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x0b, 0x2e, 0x73, 0x74, 0x61, 0x74, 0x65, 0x2e, 0x50, 0x6f, 0x6f, 0x6c, 0x52, 0x05, 0x50,
	0x6f, 0x6f, 0x6c, 0x73, 0x12, 0x1c, 0x0a, 0x09, 0x53, 0x6c, 0x61, 0x73, 0x68, 0x69, 0x6e, 0x67,
	0x73, 0x18, 0x08, 0x20, 0x03, 0x28, 0x04, 0x52, 0x09, 0x53, 0x6c, 0x61, 0x73, 0x68, 0x69, 0x6e,
	0x67, 0x73, 0x22, 0xb7, 0x01, 0x0a, 0x0d, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x50, 0x72, 0x6f, 0x64,
	0x75, 0x63, 0x65, 0x72, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04,
	0x52, 0x02, 0x49, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x50, 0x75, 0x62, 0x4b, 0x65, 0x79, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0c, 0x52, 0x06, 0x50, 0x75, 0x62, 0x4b, 0x65, 0x79, 0x12, 0x18, 0x0a, 0x07,
	0x42, 0x61, 0x6c, 0x61, 0x6e, 0x63, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x04, 0x52, 0x07, 0x42,
	0x61, 0x6c, 0x61, 0x6e, 0x63, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x53, 0x74, 0x61, 0x6b, 0x65, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x04, 0x52, 0x05, 0x53, 0x74, 0x61, 0x6b, 0x65, 0x12, 0x18, 0x0a, 0x07,
	0x53, 0x6c, 0x61, 0x73, 0x68, 0x65, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x53,
	0x6c, 0x61, 0x73, 0x68, 0x65, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x41, 0x63, 0x74, 0x69, 0x76, 0x65,
	0x18, 0x06, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x41, 0x63, 0x74, 0x69, 0x76, 0x65, 0x12, 0x1c,
	0x0a, 0x09, 0x45, 0x78, 0x69, 0x74, 0x45, 0x70, 0x6f, 0x63, 0x68, 0x18, 0x07, 0x20, 0x01, 0x28,
	0x04, 0x52, 0x09, 0x45, 0x78, 0x69, 0x74, 0x45, 0x70, 0x6f, 0x63, 0x68, 0x22, 0x70, 0x0a, 0x04,
	0x50, 0x6f, 0x6f, 0x6c, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04,
	0x52, 0x02, 0x49, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x41, 0x63, 0x74, 0x69, 0x76, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x41, 0x63, 0x74, 0x69, 0x76, 0x65, 0x12, 0x16, 0x0a, 0x06,
	0x50, 0x75, 0x62, 0x4b, 0x65, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x06, 0x50, 0x75,
	0x62, 0x4b, 0x65, 0x79, 0x12, 0x28, 0x0a, 0x0f, 0x53, 0x6f, 0x72, 0x74, 0x65, 0x64, 0x43, 0x6f,
	0x6d, 0x6d, 0x69, 0x74, 0x74, 0x65, 0x65, 0x18, 0x04, 0x20, 0x03, 0x28, 0x04, 0x52, 0x0f, 0x53,
	0x6f, 0x72, 0x74, 0x65, 0x64, 0x43, 0x6f, 0x6d, 0x6d, 0x69, 0x74, 0x74, 0x65, 0x65, 0x22, 0xf0,
	0x01, 0x0a, 0x0a, 0x42, 0x65, 0x61, 0x63, 0x6f, 0x6e, 0x44, 0x75, 0x74, 0x79, 0x12, 0x2e, 0x0a,
	0x04, 0x54, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1a, 0x2e, 0x73, 0x74,
	0x61, 0x74, 0x65, 0x2e, 0x42, 0x65, 0x61, 0x63, 0x6f, 0x6e, 0x44, 0x75, 0x74, 0x79, 0x2e, 0x44,
	0x75, 0x74, 0x79, 0x54, 0x79, 0x70, 0x65, 0x52, 0x04, 0x54, 0x79, 0x70, 0x65, 0x12, 0x1c, 0x0a,
	0x09, 0x43, 0x6f, 0x6d, 0x6d, 0x69, 0x74, 0x74, 0x65, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04,
	0x52, 0x09, 0x43, 0x6f, 0x6d, 0x6d, 0x69, 0x74, 0x74, 0x65, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x53,
	0x6c, 0x6f, 0x74, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x04, 0x52, 0x05, 0x53, 0x6c, 0x6f, 0x74,
	0x74, 0x12, 0x1c, 0x0a, 0x09, 0x46, 0x69, 0x6e, 0x61, 0x6c, 0x69, 0x7a, 0x65, 0x64, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x08, 0x52, 0x09, 0x46, 0x69, 0x6e, 0x61, 0x6c, 0x69, 0x7a, 0x65, 0x64, 0x12,
	0x24, 0x0a, 0x0d, 0x50, 0x61, 0x72, 0x74, 0x69, 0x63, 0x69, 0x70, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x18, 0x05, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0d, 0x50, 0x61, 0x72, 0x74, 0x69, 0x63, 0x69, 0x70,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x3a, 0x0a, 0x08, 0x44, 0x75, 0x74, 0x79, 0x54, 0x79, 0x70,
	0x65, 0x12, 0x0f, 0x0a, 0x0b, 0x41, 0x74, 0x74, 0x65, 0x73, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x10, 0x00, 0x12, 0x0c, 0x0a, 0x08, 0x50, 0x72, 0x6f, 0x70, 0x6f, 0x73, 0x61, 0x6c, 0x10, 0x01,
	0x12, 0x0f, 0x0a, 0x0b, 0x41, 0x67, 0x67, 0x72, 0x65, 0x67, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x10,
	0x02, 0x22, 0x6b, 0x0a, 0x10, 0x45, 0x78, 0x65, 0x63, 0x75, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x75,
	0x6d, 0x6d, 0x61, 0x72, 0x79, 0x12, 0x16, 0x0a, 0x06, 0x50, 0x6f, 0x6f, 0x6c, 0x49, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x06, 0x50, 0x6f, 0x6f, 0x6c, 0x49, 0x64, 0x12, 0x14, 0x0a,
	0x05, 0x45, 0x70, 0x6f, 0x63, 0x68, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x05, 0x45, 0x70,
	0x6f, 0x63, 0x68, 0x12, 0x29, 0x0a, 0x06, 0x44, 0x75, 0x74, 0x69, 0x65, 0x73, 0x18, 0x03, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x73, 0x74, 0x61, 0x74, 0x65, 0x2e, 0x42, 0x65, 0x61, 0x63,
	0x6f, 0x6e, 0x44, 0x75, 0x74, 0x79, 0x52, 0x06, 0x44, 0x75, 0x74, 0x69, 0x65, 0x73, 0x22, 0xe0,
	0x02, 0x0a, 0x14, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x4e, 0x65, 0x77, 0x50, 0x6f, 0x6f, 0x6c,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x04, 0x52, 0x02, 0x49, 0x64, 0x12, 0x41, 0x0a, 0x06, 0x53, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x29, 0x2e, 0x73, 0x74, 0x61, 0x74, 0x65, 0x2e,
	0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x4e, 0x65, 0x77, 0x50, 0x6f, 0x6f, 0x6c, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x2e, 0x4e, 0x65, 0x77, 0x50, 0x6f, 0x6f, 0x6c, 0x53, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x52, 0x06, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x1e, 0x0a, 0x0a, 0x53, 0x74,
	0x61, 0x72, 0x74, 0x45, 0x70, 0x6f, 0x63, 0x68, 0x18, 0x03, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0a,
	0x53, 0x74, 0x61, 0x72, 0x74, 0x45, 0x70, 0x6f, 0x63, 0x68, 0x12, 0x1a, 0x0a, 0x08, 0x45, 0x6e,
	0x64, 0x45, 0x70, 0x6f, 0x63, 0x68, 0x18, 0x04, 0x20, 0x01, 0x28, 0x04, 0x52, 0x08, 0x45, 0x6e,
	0x64, 0x45, 0x70, 0x6f, 0x63, 0x68, 0x12, 0x30, 0x0a, 0x13, 0x4c, 0x65, 0x61, 0x64, 0x65, 0x72,
	0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x65, 0x72, 0x18, 0x05, 0x20,
	0x01, 0x28, 0x04, 0x52, 0x13, 0x4c, 0x65, 0x61, 0x64, 0x65, 0x72, 0x42, 0x6c, 0x6f, 0x63, 0x6b,
	0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x65, 0x72, 0x12, 0x22, 0x0a, 0x0c, 0x43, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x50, 0x75, 0x62, 0x4b, 0x65, 0x79, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0c,
	0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x50, 0x75, 0x62, 0x4b, 0x65, 0x79, 0x12, 0x24, 0x0a, 0x0d,
	0x50, 0x61, 0x72, 0x74, 0x69, 0x63, 0x69, 0x70, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x07, 0x20,
	0x01, 0x28, 0x0c, 0x52, 0x0d, 0x50, 0x61, 0x72, 0x74, 0x69, 0x63, 0x69, 0x70, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x22, 0x3d, 0x0a, 0x0d, 0x4e, 0x65, 0x77, 0x50, 0x6f, 0x6f, 0x6c, 0x53, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x12, 0x0b, 0x0a, 0x07, 0x53, 0x74, 0x61, 0x72, 0x74, 0x65, 0x64, 0x10, 0x00,
	0x12, 0x0d, 0x0a, 0x09, 0x43, 0x6f, 0x6d, 0x70, 0x6c, 0x65, 0x74, 0x65, 0x64, 0x10, 0x01, 0x12,
	0x10, 0x0a, 0x0c, 0x55, 0x6e, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x66, 0x75, 0x6c, 0x10,
	0x02, 0x22, 0x8b, 0x02, 0x0a, 0x09, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x42, 0x6f, 0x64, 0x79, 0x12,
	0x1a, 0x0a, 0x08, 0x50, 0x72, 0x6f, 0x70, 0x6f, 0x73, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x04, 0x52, 0x08, 0x50, 0x72, 0x6f, 0x70, 0x6f, 0x73, 0x65, 0x72, 0x12, 0x14, 0x0a, 0x05, 0x45,
	0x70, 0x6f, 0x63, 0x68, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x05, 0x45, 0x70, 0x6f, 0x63,
	0x68, 0x12, 0x47, 0x0a, 0x12, 0x45, 0x78, 0x65, 0x63, 0x75, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x75,
	0x6d, 0x6d, 0x61, 0x72, 0x69, 0x65, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x17, 0x2e,
	0x73, 0x74, 0x61, 0x74, 0x65, 0x2e, 0x45, 0x78, 0x65, 0x63, 0x75, 0x74, 0x69, 0x6f, 0x6e, 0x53,
	0x75, 0x6d, 0x6d, 0x61, 0x72, 0x79, 0x52, 0x12, 0x45, 0x78, 0x65, 0x63, 0x75, 0x74, 0x69, 0x6f,
	0x6e, 0x53, 0x75, 0x6d, 0x6d, 0x61, 0x72, 0x69, 0x65, 0x73, 0x12, 0x3b, 0x0a, 0x0a, 0x4e, 0x65,
	0x77, 0x50, 0x6f, 0x6f, 0x6c, 0x52, 0x65, 0x71, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1b,
	0x2e, 0x73, 0x74, 0x61, 0x74, 0x65, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x4e, 0x65, 0x77,
	0x50, 0x6f, 0x6f, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x52, 0x0a, 0x4e, 0x65, 0x77,
	0x50, 0x6f, 0x6f, 0x6c, 0x52, 0x65, 0x71, 0x12, 0x1c, 0x0a, 0x09, 0x53, 0x74, 0x61, 0x74, 0x65,
	0x52, 0x6f, 0x6f, 0x74, 0x18, 0x05, 0x20, 0x03, 0x28, 0x0c, 0x52, 0x09, 0x53, 0x74, 0x61, 0x74,
	0x65, 0x52, 0x6f, 0x6f, 0x74, 0x12, 0x28, 0x0a, 0x0f, 0x50, 0x61, 0x72, 0x65, 0x6e, 0x74, 0x42,
	0x6c, 0x6f, 0x63, 0x6b, 0x52, 0x6f, 0x6f, 0x74, 0x18, 0x06, 0x20, 0x03, 0x28, 0x0c, 0x52, 0x0f,
	0x50, 0x61, 0x72, 0x65, 0x6e, 0x74, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x52, 0x6f, 0x6f, 0x74, 0x22,
	0x49, 0x0a, 0x0b, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x12, 0x1c,
	0x0a, 0x09, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x52, 0x6f, 0x6f, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0c, 0x52, 0x09, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x52, 0x6f, 0x6f, 0x74, 0x12, 0x1c, 0x0a, 0x09,
	0x53, 0x69, 0x67, 0x6e, 0x61, 0x74, 0x75, 0x72, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52,
	0x09, 0x53, 0x69, 0x67, 0x6e, 0x61, 0x74, 0x75, 0x72, 0x65, 0x42, 0x08, 0x5a, 0x06, 0x2e, 0x3b,
	0x63, 0x6f, 0x72, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_src_core_types_proto_rawDescOnce sync.Once
	file_src_core_types_proto_rawDescData = file_src_core_types_proto_rawDesc
)

func file_src_core_types_proto_rawDescGZIP() []byte {
	file_src_core_types_proto_rawDescOnce.Do(func() {
		file_src_core_types_proto_rawDescData = protoimpl.X.CompressGZIP(file_src_core_types_proto_rawDescData)
	})
	return file_src_core_types_proto_rawDescData
}

var file_src_core_types_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_src_core_types_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_src_core_types_proto_goTypes = []interface{}{
	(BeaconDuty_DutyType)(0),                // 0: state.BeaconDuty.DutyType
	(CreateNewPoolRequest_NewPoolStatus)(0), // 1: state.CreateNewPoolRequest.NewPoolStatus
	(*State)(nil),                           // 2: state.State
	(*BlockProducer)(nil),                   // 3: state.BlockProducer
	(*Pool)(nil),                            // 4: state.Pool
	(*BeaconDuty)(nil),                      // 5: state.BeaconDuty
	(*ExecutionSummary)(nil),                // 6: state.ExecutionSummary
	(*CreateNewPoolRequest)(nil),            // 7: state.CreateNewPoolRequest
	(*BlockBody)(nil),                       // 8: state.BlockBody
	(*BlockHeader)(nil),                     // 9: state.BlockHeader
}
var file_src_core_types_proto_depIdxs = []int32{
	3, // 0: state.State.BlockProducers:type_name -> state.BlockProducer
	4, // 1: state.State.Pools:type_name -> state.Pool
	0, // 2: state.BeaconDuty.Type:type_name -> state.BeaconDuty.DutyType
	5, // 3: state.ExecutionSummary.Duties:type_name -> state.BeaconDuty
	1, // 4: state.CreateNewPoolRequest.Status:type_name -> state.CreateNewPoolRequest.NewPoolStatus
	6, // 5: state.BlockBody.ExecutionSummaries:type_name -> state.ExecutionSummary
	7, // 6: state.BlockBody.NewPoolReq:type_name -> state.CreateNewPoolRequest
	7, // [7:7] is the sub-list for method output_type
	7, // [7:7] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_src_core_types_proto_init() }
func file_src_core_types_proto_init() {
	if File_src_core_types_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_src_core_types_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*State); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_src_core_types_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BlockProducer); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_src_core_types_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Pool); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_src_core_types_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BeaconDuty); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_src_core_types_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ExecutionSummary); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_src_core_types_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateNewPoolRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_src_core_types_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BlockBody); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_src_core_types_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BlockHeader); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_src_core_types_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_src_core_types_proto_goTypes,
		DependencyIndexes: file_src_core_types_proto_depIdxs,
		EnumInfos:         file_src_core_types_proto_enumTypes,
		MessageInfos:      file_src_core_types_proto_msgTypes,
	}.Build()
	File_src_core_types_proto = out.File
	file_src_core_types_proto_rawDesc = nil
	file_src_core_types_proto_goTypes = nil
	file_src_core_types_proto_depIdxs = nil
}
